### ISSUE TITLE
which edit view does a file get opened into?  commands should use one closest to main tabs..

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#1]
Current behavior is to rotate, i.e. first file in left panel, second in right, third in left and so on IF you use the "view" context menu item (note that the file is editable as well as viewable).

But if you use the "Edit" menubar item the file is always opened in left panel.

Suggest we use "edit" for writable files and "view" for read-only and have edit-left and edit-right or something like that in context menu and double-click for left and alt/option double-click for right or something like that from context menu. For edit menubar item option when selecting would also open file into right window.

**Comment by rohrlich** [comment]
For non-emacs users :)

**Comment by rohrlich** [comment]
Suggest for "Find" (which by the way works wonderfully!) that displaying of found items (by clicking on link) always open the file in the right side textview if two are open. The use case that comes to mind is having code I'm editing in the left view and using the right view to find something relevant that I need for the code I'm editing.

**Comment by rcoreilly** [comment]
I personally like the current behavior.  If I'm "browsing" in the file browser, and I double-click there, I want to "add" a new edit to whatever I already have -- my focus is not so clearly on the current active view.

If however I use Edit toolbar or Ctrl-X b, then my focus is more on active view, and it opens there (note: it is now much clearer which is active, and it always opens in *active*, not left).

I like the further suggestion that *all* links should open in right edit (if it isn't collapsed).  I'll do that.

**Comment by rohrlich** [comment]
Ok! Now that I understand it I like it :)

Yes the active view is now MUCH clearer!
