### ISSUE TITLE
Symbols View needs search

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#101]

**Comment by rohrlich** [comment]
Done and works well - give it a try

**Comment by rcoreilly** [comment]
Great!  this is really super useful! 

Couple of remaining things:
* when I hit the x to clear the textfield, it should reset to full unfiltered list
* should add a UpdateStart / end around the container of the treeview (and the textline for the search) the whole frame thing that is in the tab -- it isn't updating scrollbar or the textline width dynamically.
* strange: pull up go emergent, go into basic/leabra (I opened layer.go), then do Symbols -- I typed in "Clamp" and it shows me various clamp things but NOT ClampParams, which nevertheless is shown in the full unfiltered tree.
* also it would be good to alpha sort the symbol list overall..

**Comment by rcoreilly** [comment]
There is that function that sorts first by "kind" (type, function, var, etc) and then alpha after that -- that seems like the best, no?

**Comment by rohrlich** [comment]
All done other than the scrollbar update issue. I'm not sure where the updates go that would fix the problem which I think exists also for FindView and SpellView. What about solving this as part of issue #104

**Comment by rcoreilly** [comment]
scrollbar fixed -- per https://github.com/goki/gi/wiki/Layout  you need to set a "height" property for an element to get its own local scrollbars..
