### ISSUE TITLE
Main Tabs - Don't scroll the toolbars

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#104]
The toolbars in the Main Tabs should be fixed at the top. I was going to fix this problem for the SymbolsView but I see the same problem with FindView. In the FindView case only the results should scroll - it's a textview. In the symbols case the scrolling portion is a frame with a tree.

Can this be fixed with the current api?

**Comment by rcoreilly** [comment]
this is all fixed btw -- all depends on setting a default size for scrollable area per discussion in gi.Layout on gi wiki.
