### ISSUE TITLE
Resizing main tab split opens 2nd edit 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#106]
Sometimes when my split is nav, edit, main tab (i.e. "small screen" split) and I try to resize by dragging splitter between edit and main tab frames the second edit frame is opened instead!

**Comment by rohrlich** [comment]
Yes perhaps I did. In any case, the user doesn't know there is an invisible splitter. Suggest dropping the idea of uncollapsing via the splitter as it seems very natural to go to the split menu and change the view.

**Comment by rcoreilly** [comment]
just implemented major split view improvement: double-click support to collapse and restore, and, critically, multiple splitters each move down (across) so they are always distinct when overlapping.  this makes it very usable and addresses these issues.
