### ISSUE TITLE
Auto save issues

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#107]
Gide crashed so I finally needed the auto-save file.

Problem 0 - I've always found the "Ignore and Overwrite" dialog you get opening a file that has an auto-save sibling confusing because the direction of "overwrite" isn't clear.

Problem 1 - Wasn't able to search it (to check for recent changes) because the file isn't found

Problem 2 - The options on the File Changed on Disk buttons could use tool tips to make the actions clearer. There is potential loss of data here. "Ignore and proceed" is especially unclear as to the consequences.

Problem 3 - Dialog title is the same for every file - always "File Changed on Disk" - the text of the dialog does at least have the file name.

I'm happy to take this one when I have a bit of time.

**Comment by rohrlich** [comment]
Another opportunity - this time I opened the second edit window so I could compare the 2 versions and I noticed that the diffs tab had opened which is really good! I think I missed that the first time.

**Comment by rcoreilly** [comment]
You can't easily add tooltips to the ChoiceDialog, but I made the buttons even more verbose so hopefully it is clear now!
