### ISSUE TITLE
add spell checking with completion

### ISSUE THREAD

**Issue by rcoreilly** [goki/gide#11]
"hunspell" seems like main opensource spell checking framework - original is in C / C++, but there is a golang port of unknown quality:  https://github.com/client9/gospell

this is a dictionary for hunspell that we could try:

https://github.com/marcoagpinto/aoo-mozilla-en-dict/blob/master/en_US%20(Kevin%20Atkinson)/README_en_US.txt

hunspell site:  https://github.com/hunspell/hunspell

this is an interesting, very fast alternative but not clear how it would work with hunspell dictionary?  needs training?  https://github.com/sajari/fuzzy

need both online completion-based spellcheck and a separate overall spell-check doc.

can add spell checking as an option in the Langs config -- appropriate for some langs (.tex, .md) but not others (program code, although it could be selectively turned on for comments I guess)

**Comment by rohrlich** [comment]
I've started on this using gospell. The dictionary from kevin atkinson didn't parse so I'm using a different dictionary. 

For separate overall spell-check are you thinking about an interface like you have for find with links?

For the completion based UI are you thinking of completion suggestions based on the dictionary?

**Comment by rcoreilly** [comment]
yep and yep for your questions.

**Comment by rohrlich** [comment]
• It doesn't seem that gospell actually makes suggestions :( 
--  but I can have ui that let's you enter the correction, add the word to personal dictionary, etc. even without suggestions.
• It also doesn't return the character position but that is easily added, the code hasn't been touched in 3 years!
• For the completion part I can just use the dictionary itself which has about 50,000 entries, there are bigger ones, and to make it usable not attempt completion until the 3rd character is typed. My original example used a list of 1000 words.

**Comment by rcoreilly** [comment]
hmm.  so there is no api to get close matches?  maybe want to give fuzzy a try -- I think it does give matches?

**Comment by rohrlich** [comment]
I've looked at every func in gospell and none provide suggestions! Fuzzy looks interesting, though it is another repository that hasn't been touched in years. I'll give it a try.

**Comment by rohrlich** [comment]
I've done some experiments and I think this will work well with some iteration. I see a few issues but nothing serious and the code looks good to work with. I did some more googling and I don'

**Comment by rohrlich** [comment]
Hope to check in working spell check tomorrow morning.

**Comment by rcoreilly** [comment]
I'm not sure if this is an either-or or "both" question?  both sounds good to me!

**Comment by rohrlich** [comment]
yes, I do also.

Suggest we have a menu item under edit to enable/disable auto-completion and then allow it to be invoked regardless if the user enters KeyFunComplete. Then it is always available but not intrusive and going to prefs for the occasional usage would be too bothersome.

**Comment by rohrlich** [comment]
We now have text completion but we don't yet have inline spelling correction. I thought the suggestions would show up but I may need to configure differently, not sure yet.

**Comment by rohrlich** [comment]
Done - specific issues will be filed separately
