### ISSUE TITLE
Find doesn't work if you don't have tabs frame 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#111]
One of my splits is "Nav and Edit Only" which I sometimes use to have a narrow window leaving room for my pdf view in another window. If the tab frame is not visible Find doesn't work but I think it should.

I got to this because control+s is for some reason getting mapped to Save instead of Search.

**Comment by rcoreilly** [comment]
kinda need tabs to be opened for this.  not sure of a reasonable workaround.
