### ISSUE TITLE
Symbols view not responding correctly to keys

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#114]
You should be able to navigate the symbols tree with keyFunMoveUp/Down and use Enter to select.

**Comment by rohrlich** [comment]
Also typing into the "find" field of the symbols panel is not working.

I'll look into these problems.

**Comment by rohrlich** [comment]
I fixed the filtering bug which should have been entered as a separate bug :)

**Comment by rohrlich** [comment]
Considering the key navigation low priority for now.

**Comment by rcoreilly** [comment]
you can't really do key navigation b/c that drives selection events which take you immediately to the selected symbol.. you can use tab / shift-tab but that is probably not that useful.

could have some kind of navigation-without-selection but not clear if that is generally useful -- would require significant change to default behavior and some kind of "mode" flag to switch between..

so basically going to close this at this point.

**Comment by rohrlich** [comment]
I'm good with closing.
