### ISSUE TITLE
Spell check missing some misspelled words

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#115]
If I run spell check from the Spelling tab it is not showing "distange" as an error but if I type "distange" the inline check shows an error and produces the correct list of suggestions.

**Comment by rcoreilly** [comment]
I'm getting good corresp now with rewritten version that uses much more similar code paths.  open again if see again.

**Comment by rcoreilly** [comment]
and now I found that the regexp's were causing a LOT of words to be missed!  now it really seems to be checking everything..
