### ISSUE TITLE
filetree: renaming a directory does not update internal paths

### ISSUE THREAD

**Issue by rcoreilly** [goki/gide#116]
I just renamed a directory (emergent/basic -> emergent/leabra) and when I clicked on files in there, it couldn't find them as it was still looking in emergent/basic -- this is after a manual UpdateFiles. 

* rename on dir should auto-update
* and update should notice different file name!

**Comment by rcoreilly** [comment]
also all the files in that dir got marked for deletion in git!  i thought git was robust to these kinds of renames but apparently not.  need to fix that somehow..

**Comment by rohrlich** [comment]
I think git does a delete and then an add - that would be the correct behavior I think

**Comment by rohrlich** [comment]
Ok, I'll fix this. I don't think I ever handled the dir rename, just the file rename.

**Comment by rcoreilly** [comment]
now fixed -- does the update and closes any open edits in gide.
