### ISSUE TITLE
Unable to locate icons when using multiple GOPATHs

### ISSUE THREAD

**Issue by mewmew** [goki/gide#12]
Hi,

I felt really quite happy to discover GoKi and GoGI and GIde today! Wow, what a treasure. I'll dive deeper into the code base in the time to come.

For now, I wanted to report back on a few issues I noticed when trying to get Gide running. Note, I could `go get` and compile Gide just fine. However, when running Gide, the following errors are displayed:

```
$ gide
gi.IconSet: error accessing path "/home/u/goget:/home/u/Desktop/go/src/github.com/goki/gi/icons": lstat /home/u/goget:/home/u/Desktop/go/src/github.com/goki/gi/icons: no such file or directory
2018/10/06 18:56:10 gi.IconSet: error walking the path "/home/u/goget:/home/u/Desktop/go/src/github.com/goki/gi/icons": lstat /home/u/goget:/home/u/Desktop/go/src/github.com/goki/gi/icons: no such file or directory
```

This is since my GOPATH contains multiple paths using a `:` separated path list.

```
$ go env | grep GOPATH
GOPATH="/home/u/goget:/home/u/Desktop/go"
```

To solve this issue you can do something like [goutil.SrcDir](https://github.com/mewkiz/pkg/blob/master/goutil/gotuil.go#L15):

```go
// SrcDir tries to locate dir in GOPATH/src/ or GOROOT/src/pkg/ and returns its
// full path. GOPATH may contain a list of paths.
func SrcDir(dir string) (absDir string, err error) {
	for _, srcDir := range build.Default.SrcDirs() {
		absDir = filepath.Join(srcDir, dir)
		finfo, err := os.Stat(absDir)
		if err == nil && finfo.IsDir() {
			return absDir, nil
		}
	}
	return "", errors.Errorf("unable to locate directory (%q) in GOPATH/src/ (%q) or GOROOT/src/pkg/ (%q)", dir, os.Getenv("GOPATH"), os.Getenv("GOROOT"))
}
```

**Note:** the `SrcDir` function is very simple so re-implement or copy it, rather than adding `goutil` as a dependency. The `mewkiz/pkg` repo of which the `goutil` package is part of, is released in the public domain, just so you know.

Cheerful regards,
Robin

**Comment by rcoreilly** [comment]
thanks for all the bug finds!  should all be fixed in latest checkin.
