### ISSUE TITLE
List of completion issues circa 1/2020

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#125]

**Comment by rcoreilly** [comment]
give me another day before filing these -- still a bit of work to do!   then I'll show you how to fix them :)

**Comment by rcoreilly** [comment]
ps. you *should* give the filtered a good test -- it has been working perfectly for me so far with the recent fixes.

**Comment by rcoreilly** [comment]
Here's my list of known issues -- some of which I'm NOT going to fix in next couple of days (btw, ss.Net.C* now gives right results):

* `ra25.go`: `ly := ss.Net.LayerByName(lnm).(leabra.LeabraLayer).AsLeabra()` -- this is high pri -- will fix -- seems like an issue dealing with interfaces which I haven't done anything with..

* 2nd or later vars in multiple assignment are not getting registered by parser:
`pi/golang/complete.go`: `start, last := gl.CompleteAstStart(lfs.ParseState.Ast)` -- shouldn't be too hard to fix parser -- not sure why not working.

* `gi/menus.go`: `var CustomAppMenuFunc = (func(m *Menu, win *Window))(nil)`

* `pi/golang/types.go`: `tyast, err := ty.Ast.(*parse.Ast).ChildAstTry(1)`

* `pi/syms/type.go`: `el := &(*te)[i]`

* various: `C.*` -- not parsing C!  should just ignore silently probably

In addition, I haven't done much at all with the actual completer logic that finds the right bits to complete -- this logic is MUCH simpler than the type inference part and will be done tomorrow night presumably -- recommend just using the `ctrl+.` manual completion-on-demand mode at this point.

**Comment by rcoreilly** [comment]
A major remaining issue is that incremental edits do not update symbols used in completion.  Can do some local hackery to try to make this work incrementally by adding symbols from the ParseLine file state, but this will probably run aground at some point.  

better idea would be to have *2 separate FileStates* for each file, one of which is active, and the other is periodically updated in a separate thread, with a lock on that process.  when it finishes the background update, it just swaps in as the active file state.  They both operate on the exact same Src bytes etc so it is just the parse state etc that is separately updated.  seems good.

**Comment by rcoreilly** [comment]
Ok, FileStates now in place -- looking pretty solid!

another idea: for completion maybe just nuke any spaces *before parsing* so expressions can be parsed without barfing from if or field context or other such things.

**Comment by rcoreilly** [comment]
not getting updates from a package while working on another file -- currently working on giv/textbuf.go and adding a bunch of stuff to new sub-package textbuf -- textbuf.go not getting updates...  should..

**Comment by rcoreilly** [comment]
`piview.go:226`

`fs := &pv.TestBuf.PiState` does not return correct type, but getting rid of & works

`pfs := fs.Proc()` not getting return type -- was due to compile errors.

**Comment by rcoreilly** [comment]
fixed `&` case. still trying to track down update issue -- works in basic tests of course..

**Comment by rcoreilly** [comment]
update now working on new code dirs etc.  was probably combination of some of above more specific issues.

now: not completing on interface methods at all.

**Comment by rcoreilly** [comment]
gide/debugview.go: dv method receiver not completing.  feel like I saw this before too

**Comment by rcoreilly** [comment]
it was merging of type symbols.  fixed now -- use ones with Kind set! also with symbols.  still some issues:

```go
gide/debugview.go:201:
	sv := tb.RecycleTab("Stack", KiT_StackView, false).(*StackView)
gide/gidebug/gidelve/gidelve.go: GiDelve not resolving
```

**Comment by rcoreilly** [comment]
```go
giv/textview.go:3439
(gi.Prefs.Colors.Select
```

not completing on select but yes getting colors..  also not getting updated Contains in texbuf.Region. despite many attempts to get it to refresh.  probably new change needs to merge els?

**Comment by rohrlich** [comment]
completion inside brackets should be finding all vars but in code below where you see "..." the completion list is the single item "splits" until you type some character which brings up the properly filtered list. My recollection is that we don't automatically populate if there are more than N items but forcing the list should not be displaying a single item.

splits := strings.SplitAfterN(s, "/", cnt+1)
			ss.SimMat.Rows[r] = splits[...

**Comment by rohrlich** [comment]
> ps. you _should_ give the filtered a good test -- it has been working perfectly for me so far with the recent fixes.

Not sure what you mean by "the filtered"

**Comment by rcoreilly** [comment]
"FileTree" :). will look into above case.

**Comment by rcoreilly** [comment]
don't do completion inside of strings!

**Comment by rcoreilly** [comment]
still getting some failures to find function context when typing at end of a function (as is very common)

**Comment by rcoreilly** [comment]
btw I'm going to close this and make separate issues for anything I don't fix.  I put rocket symbols for everything that is already fixed, and eyeballs for not fixed yet.

main practical issue is not getting scope and end of method, so I'm going to focus on that one first.
