### ISSUE TITLE
Moving keymap prefs causes failure on startup

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#126]
github.com/goki/gi/gi.(*TextRender).SetHTMLPre(0xc000181140, 0xc0006dda40, 0x2, 0x20, 0xc000180830, 0xc000180890, 0xc000180914, 0xc00070d770)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/text.go:1646 +0x4b3
github.com/goki/gi/gi.(*TextRender).SetHTML(0xc000181140, 0x4e032fe, 0x2, 0xc000180830, 0xc000180890, 0xc000180914, 0xc00070d770)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/text.go:1258 +0x150
github.com/goki/gi/gi.(*Label).SetText(0xc000180580, 0x4e032fe, 0x2)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/label.go:128 +0x2b0
github.com/goki/gi/gi.(*PartsWidgetBase).ConfigPartsSetIconLabel(0xc000204000, 0x0, 0x0, 0x4e032fe, 0x2, 0xffffffffffffffff, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:844 +0x1fb
github.com/goki/gi/gi.(*ButtonBase).ConfigParts(0xc000204000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:584 +0x2a7
github.com/goki/gi/gi.(*ButtonBase).SetText(0xc000204000, 0x4e032fe, 0x2)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:205 +0x127
github.com/goki/gi/gi.(*Dialog).StdButtonConnect(0xc0006f8a80, 0xc000560001, 0xc000539600)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:404 +0x1ca
github.com/goki/gi/gi.(*Dialog).StdDialog(0xc0006f8a80, 0x4e39f2f, 0xe, 0xc00003c230, 0x50, 0xc0006d0001)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:439 +0x133
github.com/goki/gi/gi.NewStdDialog(0x4e39f2f, 0xe, 0xc00003c230, 0x50, 0x0, 0x1, 0xc00003c230)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:470 +0x159
github.com/goki/gi/gi.PromptDialog(0x0, 0x4e39f2f, 0xe, 0xc00003c230, 0x50, 0x0, 0xc000700001, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:510 +0x5b
github.com/goki/gide/gide.(*KeyMaps).OpenJSON(0x5e98af0, 0xc0000cc090, 0x30, 0xc0000cc090, 0x30)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/keyfun.go:332 +0x120
github.com/goki/gide/gide.(*KeyMaps).OpenPrefs(0x5e98af0, 0x186, 0x386)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/keyfun.go:360 +0xbb
github.com/goki/gide/gide.(*Preferences).Open(0x5e9bb20, 0x8, 0x281)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/prefs.go:150 +0x1c5
github.com/goki/gide/gide.InitPrefs()
	/Users/rohrlich/go/src/github.com/goki/gide/gide/prefs.go:76 +0x107
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:39 +0xd0
github.com/goki/gi/gi.(*TextRender).SetHTMLPre(0xc000181140, 0xc0006dda40, 0x2, 0x20, 0xc000180830, 0xc000180890, 0xc000180914, 0xc00070d770)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/text.go:1646 +0x4b3
github.com/goki/gi/gi.(*TextRender).SetHTML(0xc000181140, 0x4e032fe, 0x2, 0xc000180830, 0xc000180890, 0xc000180914, 0xc00070d770)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/text.go:1258 +0x150
github.com/goki/gi/gi.(*Label).SetText(0xc000180580, 0x4e032fe, 0x2)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/label.go:128 +0x2b0
github.com/goki/gi/gi.(*PartsWidgetBase).ConfigPartsSetIconLabel(0xc000204000, 0x0, 0x0, 0x4e032fe, 0x2, 0xffffffffffffffff, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:844 +0x1fb
github.com/goki/gi/gi.(*ButtonBase).ConfigParts(0xc000204000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:584 +0x2a7
github.com/goki/gi/gi.(*ButtonBase).SetText(0xc000204000, 0x4e032fe, 0x2)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:205 +0x127
github.com/goki/gi/gi.(*Dialog).StdButtonConnect(0xc0006f8a80, 0xc000560001, 0xc000539600)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:404 +0x1ca
github.com/goki/gi/gi.(*Dialog).StdDialog(0xc0006f8a80, 0x4e39f2f, 0xe, 0xc00003c230, 0x50, 0xc0006d0001)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:439 +0x133
github.com/goki/gi/gi.NewStdDialog(0x4e39f2f, 0xe, 0xc00003c230, 0x50, 0x0, 0x1, 0xc00003c230)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:470 +0x159
github.com/goki/gi/gi.PromptDialog(0x0, 0x4e39f2f, 0xe, 0xc00003c230, 0x50, 0x0, 0xc000700001, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:510 +0x5b
github.com/goki/gide/gide.(*KeyMaps).OpenJSON(0x5e98af0, 0xc0000cc090, 0x30, 0xc0000cc090, 0x30)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/keyfun.go:332 +0x120
github.com/goki/gide/gide.(*KeyMaps).OpenPrefs(0x5e98af0, 0x186, 0x386)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/keyfun.go:360 +0xbb
github.com/goki/gide/gide.(*Preferences).Open(0x5e9bb20, 0x8, 0x281)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/prefs.go:150 +0x1c5
github.com/goki/gide/gide.InitPrefs()
	/Users/rohrlich/go/src/github.com/goki/gide/gide/prefs.go:76 +0x107
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:39 +0xd0

**Comment by rohrlich** [comment]
This is actually a problem caused by fonts not being found. I'm closing this and opening an issue in goki/gi

**Comment by rcoreilly** [comment]
it shouldn't be opening a prompt dialog at this point in the startup sequence.  I just removed that call and it should fix it.
