### ISSUE TITLE
Change "splits" works from view/splits menu in menubar but not from "splits" button/menu

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#128]

**Comment by rcoreilly** [comment]
that's new -- used to work as of not long ago..

**Comment by rcoreilly** [comment]
it just did work for me now.  not sure when it works and doesn't.

**Comment by rohrlich** [comment]
I thought that the menu failure was a no-op but in trying it now I think the problem is in the getting or setting of values. Let me know if you want me to take a look.

**Comment by rcoreilly** [comment]
had multiple errors.. not sure how it ever worked.
