### ISSUE TITLE
symbolsview not refreshing based on active textview, scope selection

### ISSUE THREAD

**Issue by rcoreilly** [goki/gide#129]
always just shows the first thing that it shows..

**Comment by rohrlich** [comment]
It seems there are 2 cases and they both can fail.
1 - you change textviews but the symbols view doesn't update
2 - you click on a different tab and then click back to the symbols view tab
For the second I could connect to the TabSelected signal and whatever signal there is for active textview change
Or we could just have a refresh button but the signal approach should work.

**Comment by rcoreilly** [comment]
probably a refresh button would be good for clarity -- don't want to have to deal with stuff auto-updating when you don't even care about it -- if you're looking at it, you'll want to just hit the button to make sure.

**Comment by rohrlich** [comment]
Ok, thanks for keeping my bias toward automaticity in check :)

**Comment by rohrlich** [comment]
Added refresh button and fixed the scope problem
