### ISSUE TITLE
debug VarView: add ability to dynamically follow pointers

### ISSUE THREAD

**Issue by rcoreilly** [goki/gide#131]
It isn't too hard to just incrementally follow individual expressions in the GetVar (which takes full path expressions) -- so on a node that ends in a pointer, could have a button that is "follow pointer" and it just does that..

**Comment by rohrlich** [comment]
Pretty sure what you are describing is what I need in case like the one shown in the picture where I would like to get the instance data. Looks like the api is there in reading the delve api doc.
<img width="758" alt="Screen Shot 2020-02-11 at 9 54 24 PM" src="https://user-images.githubusercontent.com/22350787/74307434-272d7380-4d1a-11ea-8c62-a73fa4ad1a62.png">

**Comment by rcoreilly** [comment]
Yep..

**Comment by rcoreilly** [comment]
much improved docs now on some things:

https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md

Loading more of a Variable

You can also give the user an option to continue loading an incompletely loaded variable. To load a struct that wasn't loaded automatically evaluate the expression returned by:

fmt.Sprintf("*(*%q)(%#x)", v.Type, v.Addr)
where v is the variable that was truncated.

To load more elements from an array, slice or string:

fmt.Sprintf("(*(*%q)(%#x))[%d:]", v.Type, v.Addr, len(v.Children))
To load more elements from a map:

fmt.Sprintf("(*(*%q)(%#x))[%d:]", v.Type, v.Addr, len(v.Children)/2)

**Comment by rcoreilly** [comment]
now has FollowPtr button -- works!  display could be cleaner but good enough for now.
