### ISSUE TITLE
Crash invoking Debug

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#134]
I got this again. Steps to recreate were:
- open project
- open a .go file
- build project project
- select "debug"

2020/02/08 20:52:38 Gi Debug: File type Csv not supported

panic: runtime error: index out of range [0] with length 0

goroutine 253 [running]:
github.com/goki/gide/gide.(*Command).RunAfterPrompts(0xc00073d500, 0x51e1b80, 0xc0007b5500, 0xc00f02b200)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/commands.go:365 +0x550
github.com/goki/gide/gide.(*Command).Run(0xc00073d500, 0x51e1b80, 0xc0007b5500, 0xc00f02b200)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/commands.go:330 +0x2f2
github.com/goki/gide/gidev.(*GideView).ExecCmdName(0xc0007b5500, 0x0, 0x0, 0x6000101)
	/Users/rohrlich/go/src/github.com/goki/gide/gidev/gideview.go:1342 +0xd1
github.com/goki/gide/gidev.(*GideView).ExecCmds(0xc0007b5500, 0xc0000427c0, 0x2, 0x4, 0x10005150101)
	/Users/rohrlich/go/src/github.com/goki/gide/gidev/gideview.go:1455 +0x7e
github.com/goki/gide/gidev.(*GideView).Build.func1()
	/Users/rohrlich/go/src/github.com/goki/gide/gidev/gideview.go:1473 +0x55
github.com/goki/gide/gidev.(*GideView).SaveAllCheck(0xc0007b5500, 0xc0139ebe01, 0xc0139ebec0, 0x4ed5e20)
	/Users/rohrlich/go/src/github.com/goki/gide/gidev/gideview.go:320 +0x81
github.com/goki/gide/gidev.(*GideView).Build(0xc0007b5500)
	/Users/rohrlich/go/src/github.com/goki/gide/gidev/gideview.go:1472 +0x7a
reflect.Value.call(0x4ed5e20, 0xc0007b5500, 0x6a13, 0x4ed9afe, 0x4, 0x0, 0x0, 0x0, 0xc00fd23aa0, 0x400f328, ...)
	/usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x4ed5e20, 0xc0007b5500, 0x6a13, 0x0, 0x0, 0x0, 0xc006f76d94, 0x0, 0xc003864a50)
	/usr/local/go/src/reflect/value.go:321 +0xb4

**Comment by rcoreilly** [comment]
The deeper reason for the crash is RunExec not pointing to a place that builds an exe.  but I just checked in a potential fix for proximal crash.  can you re-test?  I will also try to reproduce.

**Comment by rohrlich** [comment]
I will but probably it will be tomorrow.

**Comment by rohrlich** [comment]
The latest update eliminated the fix. I set the Run Exec and then invoked Debug and go this

2020/02/08 22:00:42 ERROR SignalViewport2D updating node /gide-babbling/WinVp/main-vlay/main-frame/babbling/splitview/tabs/frame/Debug audonly with Updating flag set

invoking Run did work.

**Comment by rohrlich** [comment]
oops, not "the fix" but "the crash"!

**Comment by rohrlich** [comment]
Working now.

**Comment by rohrlich** [comment]
Just got this crash with ra25 after building go proj and clicking debug.

rohrlich@MacBook-Pro-5:gide:> ./gide
2020/02/10 17:25:31 open /Users/rohrlich/Library/gide/key_maps_prefs.json: no such file or directory
Preferences Saved to prefs.json
2020/02/10 18:28:10 Gi Debug: File type Csv not supported
panic: runtime error: index out of range [0] with length 0

goroutine 2829 [running]:
github.com/goki/gi/gi.(*Layout).LayoutGrid(0xc01b3bf700)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:833 +0x5f8
github.com/goki/gi/gi.(*Layout).Layout2D(0xc01b3bf700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x41d0000000000000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1725 +0x23a
github.com/goki/gi/gi.(*Node2DBase).Layout2DChildren(0xc01b3bdb80, 0x0, 0x9)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:817 +0x167
github.com/goki/gi/gi.(*Layout).Layout2D(0xc01b3bdb80, 0x9, 0x9, 0xffffffffffffffdd, 0xffffffffffffffdd, 0x0, 0x41d00000411c0000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1734 +0xca
github.com/goki/gi/gi.(*Node2DBase).Layout2DChildren(0xc01b3bc000, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:817 +0x167
github.com/goki/gi/gi.(*Layout).Layout2D(0xc01b3bc000, 0x0, 0x0, 0xffffffffffffffe6, 0x0, 0x0, 0x41d0000000000000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1734 +0xca
github.com/goki/gi/gi.(*Node2DBase).Layout2DChildren(0xc032d5a700, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:817 +0x167
github.com/goki/gi/gi.(*Layout).Layout2D(0xc032d5a700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21f34f50)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1734 +0xca
github.com/goki/gi/giv.(*TableView).Layout2D(0xc032d5a700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x41d0000000000000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:841 +0x63
github.com/goki/gi/gi.(*Node2DBase).Layout2DChildren(0xc04ae78c00, 0x0, 0x9)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:817 +0x167
g

**Comment by rohrlich** [comment]
I'm fixing now.

**Comment by rohrlich** [comment]
Randy - The problem is in creating a debug view for an unsupported lang type. My ra25 project was set to csv. I've put in a fix that will create the debug view but makes sure its state is set to Error. You do get the error about the unsupported type on the console but maybe a dialog showing the error with explanation and not creating the debugger at all would be better.

**Comment by rcoreilly** [comment]
we could make the layout more robust too -- not sure what the ultimate cause is but I'll fix the proximal crash source now..

**Comment by rcoreilly** [comment]
yeah not creating a debug view makes sense.

**Comment by rcoreilly** [comment]
layout fixed.  doesn't crash now even without your fix, so I think we're covered!
