### ISSUE TITLE
Not stopping at breakpoint

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#135]
Possibly user error :)

- Build go project
- Click Debug
- Panel tab shows "building" then "ready"
- clicking continue starts the app
- set breakpoint on first line of code in TrialStatsTRC()
- click train

Note that this is my app - did not try with ra25

**Comment by rcoreilly** [comment]
due to the way delve works, breakpoints only "take" when stopped, so you have to hit stop, then continue..

**Comment by rohrlich** [comment]
Ok, stopping now. Are you going to add an indicator that a breakpoint was reached or is it there and I am missing it.

**Comment by rcoreilly** [comment]
it just pulls up the file and puts the cursor there, so you should see the red and yellow squares... I can also have it select the breakpoint in the breaks view.

**Comment by rohrlich** [comment]
Ok, I've played with it a bit and I suggest 2 changes as the stop on breakpoint is very subtle now.
1 - bring the gide window to the front when you hit a breakpoint
2 - highlight the entire line - moving the cursor may not be what the user wants

**Comment by rcoreilly** [comment]
now it reports the Break: # in the status, and brings the gide window to the front.

I think highlighting the line doesn't make sense -- we then have to deal with the highlight later, and new changes should make it very clear what has happened.

this cursor moving is how we do *all* of the single-stepping or any other showing of file lines from debugger, so it should be familiar pretty soon...

**Comment by rcoreilly** [comment]
assuming this is now satisfactory :)

**Comment by rohrlich** [comment]
Yes! Using right now!

On Feb 13, 2020, at 5:21 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


assuming this is now satisfactory :)
