### ISSUE TITLE
add a few key text manip functions to textbuf utils or pi/lang/golang

### ISSUE THREAD

**Issue by rcoreilly** [goki/gide#136]
* rename variable -- uses Lex tags to find actual variables instead of using raw text, so it won't confuse strings embedded in other strings -- this can be done in textbuf with tags support.  can be a very general method that takes a tag cat / subcat etc and does rename on those tags.  

* fix auto-indent.  not sure if needs to be in lang -- probably better if it is so that e.g., python can have its own custom one, but also provide a better default one in textbuf that does the right thing for bracket-based languages.  how much does it need to know about syntax?  depth lex would be very helpful here obviously.

* rectangle cut / paste -- I often want this.  key fun is already there.

* @rohrlich what else do you rely on a lot?

**Comment by rohrlich** [comment]
One that immediately comes to mind is "Find Usages", the opposite of lookup. Can use same key mapping!

**Comment by rcoreilly** [comment]
> rename variable -- uses Lex tags to find actual variables instead of using raw text, so it won't confuse strings embedded in other strings -- this can be done in textbuf with tags support. can be a very general method that takes a tag cat / subcat etc and does rename on those tags.

this is now in place -- "Lexical Items" in basic query-replace -- very effective, simple and general!

**Comment by rcoreilly** [comment]
moving this into separate tickets and closing this one -- omnibus tickets are not that useful.. 

@rohrlich for `Find Usages` -- probably you want that as a special kind of Find -- need all that same link infrastructure etc to show a list of results -- basically copy FindView  -- will be somewhat involved and I'm not sure how useful relative to just looking for the type name using existing Find framework?

or maybe better just as a way of filtering the Symbols view according to symbol type name?  

anyway, take a look at this and think about it and file a new ticket with a specific actionable plan when you get a chance.
