### ISSUE TITLE
Add "Compare with branch" to file context menu

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#138]
I find this narrow focus diff very useful!

**Comment by rcoreilly** [comment]
Yeah now I'm just going to write a quick side-by-side diff view -- should be very easy with the line number coloration feature, and this diff among others will be key to support.

**Comment by rcoreilly** [comment]
Diff VCS menu option now in place -- you can enter e.g., "-1" to get the diff from prior revision, etc.  

TODO: add "rev a" and "rev b" options so you can compare any revision to any other revision!

also, add support for blame (just dumps result of git blame in a file) , and log -- with that we have a fairly complete level of vcs functionality

**Comment by rcoreilly** [comment]
done!
