### ISSUE TITLE
Debug - Suggest not expanding the fields of structs when viewing Vars

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#139]
If I expand my sim struct it is overwhelming to see every field expanded. I'd like to see just the structs fields and then expand as needed.

**Comment by rcoreilly** [comment]
I think it really depends on what you're doing.. I've been happy with the default expansion most of the time.. we could set a param, but there is also a ctxt menu to close all and you can open from there, so maybe that's ok?  in general I don't want to add too much complexity here..

**Comment by rohrlich** [comment]
I'll use the ctxt menu.
