### ISSUE TITLE
Lookup opens the file but doesn't seem to take you to line

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#140]

**Comment by rohrlich** [comment]
The file name in the window is followed by what I believe should be the line/column info. They are always nn:nn where nn is different but wrong!
<img width="479" alt="Screen Shot 2020-02-10 at 10 19 43 PM" src="https://user-images.githubusercontent.com/22350787/74214769-a441e580-4c53-11ea-9ac4-efc8581ec3d4.png">

**Comment by rcoreilly** [comment]
start:end lines, not column. I will just omit end line as it is rare that we have it.

and the text that is shown is a direct excerpt of the relevant file, but I think it makes more sense to just always show the full file and scroll to starting line -- often you want more info anyway.

**Comment by rcoreilly** [comment]
did scrolling thing.
