### ISSUE TITLE
Deleting breakpoints from DebugView does not clear them in the editor

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#141]

**Comment by rcoreilly** [comment]
that is "deactivating" (on / off) but not "deleting".  all breakpoints will be deleted when the debugview is closed.  could go out and recolor the breaks that have been deactivated.

if you delete in the textview, then it is really deleting.

the logic is that often enough you just want to toggle and there usu aren't that many and it is just simpler to not have both delete and toggle on / off.

**Comment by rcoreilly** [comment]
I updated docs to reflect this info

**Comment by rohrlich** [comment]
I'm talking about the + - columns on the far right. I've played with this a bit more and I see that they are view only. Thus the "-" removes the item from the DebugView but then it reappears when you continue. So just drop the +/-.

**Comment by rcoreilly** [comment]
good idea -- didn't even notice those!

**Comment by rcoreilly** [comment]
done.
