### ISSUE TITLE
DebugView - column contents don't align with column headings

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#142]
Looks like the padding between columns is a pixel less than between headings. Would be good to force column separation and column widths to be whatever is set for headings. And that would also fix the problem of checkbox column headings being unreadable.

**Comment by rcoreilly** [comment]
In general it has been better in other views to have columns size to contents, not header.  You have full control over this through the use of the "width" tag which will enforce a fixed width in terms of characters.  I just added this to Breaks.
