### ISSUE TITLE
Lookup on field should take you to field, not just struct

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#143]
Also, wrong line numbers. In this case I did a lookup on ss.SimMatTick which is line 270. The line numbers show are for the comment on the ss struct.
<img width="1400" alt="Screen Shot 2020-02-11 at 12 04 09 PM" src="https://user-images.githubusercontent.com/22350787/74274491-fec85980-4cc6-11ea-9233-3f7a0fd8b4fa.png">

**Comment by rohrlich** [comment]
I'm finding quite a few lookup errors so maybe you want to explain how they work and I can fix them.

**Comment by rcoreilly** [comment]
I don't know if we have line numbers specifically for fields -- probably.  It is very type-based. you should look at goki/pi/lang/golang/complete.go for the code -- turn TraceComplete = true to see what is going on..

**Comment by rohrlich** [comment]
Will do.

**Comment by rohrlich** [comment]
Will the debugger stop in external files? I tried it and it didn't work.

**Comment by rcoreilly** [comment]
absolutely -- I've done it many times!  you just open the file, double-click as usual.

**Comment by rcoreilly** [comment]
if you have a reproducible exception, report here (or fix it! :)

**Comment by rohrlich** [comment]
Yes, working. Possibly I was running an old executable.

**Comment by rohrlich** [comment]
Closed by mistake. My "Yes working" was in reference to breakpoints in external files. The original issue is one I still need to fix.

**Comment by rohrlich** [comment]
I've been working through this for about 90 minutes and I see that for something like ss.SomeField (where I place my cursor inside SomeField) TypeFromAstExpr returns "typ" as the Sim struct. It does a piece of the field name but it isn't used so there is no chance to scroll to the actual field. Also, if I have ss.SomeField = 33 and I place my cursor after the field name then nothing is returned because "typ" is set to int.

Thus I think we should always grab the whole identifier (i.e. SomeField) no matter where the cursor is inside the word. Basically "grab word" as we do for double click in text. And there is a lot of redundancy in var names so that will make sure we aren't finding the wrong variable/field, etc.

When I return to this code I am going to look into TypeFromAstExpr()

If you decide to work on this before I get back to it please let me know.

**Comment by rcoreilly** [comment]
I won't be working on this specific issue -- for my purposes seeing the whole struct is fine.. 

```go
	start, last := gl.CompleteAstStart(lfs.ParseState.Ast, scope)
```

the last item here *should* be the field name, I think, at least in some cases..

**Comment by rohrlich** [comment]
Ok, after looking at this I see that I was confused about the behavior of lookup in gide. I see now, that for the example below, calling the lookup function on FieldB in MyFunc will take me to the declaration of structB whereas I was expecting it to take me to the declaration of FieldB where I would see it is declared as a structB and then if I want to see the declaration of structB I can do a second lookup. I'm not sure how all IDEs handle this, some have shortcuts for both types of lookup. I'll close this issue but perhaps this is something for discussion.

type structA struct {
    FieldA int
    FieldB structB
}
...
func (a *structA) MyFunc {
    a.FieldB
}

**Comment by rcoreilly** [comment]
Yeah, if you want StructA, lookup a.  Overall it seems reasonable to me that if you're looking up something, you want its type info, so e.g., structB in above example.

**Comment by rohrlich** [comment]
Yeah, first thing I tried but it didn't work. I'll file that bug now.
