### ISSUE TITLE
Suggestion - lookup should also work for selections, not just cursor

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#144]
In the case of ss.GenSimMat() I find that with GenSimMat selected lookup takes me to the ss struct and with my cursor after 'G' or anywhere up to after 't' the lookup takes me to the GenSimMat function. So I guess your algorithm is to use what is before the cursor. That seems okay if nothing is selected.

**Comment by rohrlich** [comment]
Would it be okay if we passed the entire "word" to lookup. Here are the results for 3 uses of lookup with "ss.Net.DWt"
- put cursor after D and you get inconsistent results, sometimes Network.Defaults(), sometimes Network.DeepCtxt, etc.
- put cursor after DW and you get Network.DWt, hooray!
- select DWt and you get the Network struct because effectively the cursor is before the D

I really think the lookup should be on whatever is between the dots or dot and parens or whatever the delimiter is even if there is no selection.

**Comment by rohrlich** [comment]
I can fix if you agree.

**Comment by rcoreilly** [comment]
yes agree -- basically lookup was just using the code from completion where it makes sense to use the current cursor position, but it definitely makes sense to a) use the selection if there is one, and b) use the full word.

**Comment by rohrlich** [comment]
ok, I'll do tonight

**Comment by rohrlich** [comment]
Working well.
