### ISSUE TITLE
Gide frozen when debugging

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#145]
A couple of times while debugging gide seems frozen, i.e. not accepting input from keyboard or mouse/trackpad.

No clue about what causes this behavior.

**Comment by rohrlich** [comment]
One case in which this happens sometimes is clicking restart. I'll add more info when I have it.

**Comment by rcoreilly** [comment]
any update?  maybe fixed?

**Comment by rohrlich** [comment]
I've been using GoLand to debug the speech synthesis code because the debug process is faster/smoother but I just updating and gave the Gide debugger some exercise. No freeze so I'll close.

**Comment by rcoreilly** [comment]
are there any easy-ish ways to make the Gide debugging process smoother & faster?

**Comment by rohrlich** [comment]
A couple of items that I think will be easy are:
1 - key shortcuts for stepping over/in/out (function keys in all the IDEs I've used)
2 - mouse over to see value when stopped
I'll do some side by side comparisons and give you some more comments

**Comment by rcoreilly** [comment]
great -- those are easy!  are there any conventions on function keys??

**Comment by rcoreilly** [comment]
I thought about the hover-on-value before -- it should be easy -- I'll give that a try later tonight.

**Comment by rohrlich** [comment]
Xcode has:
F6 over
F7 in
F8 out

GoLand has
F8 over
F7 in
Shift F8 out

I think the Xcode mapping is more intuitive. There are other more obscure ones that I rarely use, e.g. run to cursor.

**Comment by rohrlich** [comment]
Here are a couple of pics of what hover looks like - very similar in GoLand and Xcode. I expect the primary variable display will be easy, I'm not expecting the expanding deep dive in the second screen shot.

Thanks for considering some additional features. The Gide Debug interface is quite sufficient but working through the auditory code port I wanted all the help I could get. I have been using Gide for my modeling code.

<img width="572" alt="Screen Shot 2020-03-03 at 6 43 42 PM" src="https://user-images.githubusercontent.com/22350787/75841090-b6f69880-5d81-11ea-82ac-3b22234d33c0.png">

<img width="857" alt="Screen Shot 2020-03-03 at 6 44 00 PM" src="https://user-images.githubusercontent.com/22350787/75841072-b0682100-5d81-11ea-85ff-7e928fcfd049.png">

**Comment by rohrlich** [comment]
I could make an argument that the GoLand key mappings are more intuitive.  I'll adjust to whatever you choose.

**Comment by rohrlich** [comment]
I forgot! Need a mapping for "continue/resume". GoLand has command+option+R while Xcode has the unforgettable ctrl+command+Y, which I forget :)

**Comment by rcoreilly** [comment]
Ok I went with F6,7,8 and Ctrl+Alt+R for Cont -- helped fix shortcut infrastructure which was missing for toolbars.. And hover-vars is in place -- double-click to bring up browser for more complex vars.

**Comment by rohrlich** [comment]
Keys and hover all working great!
