### ISSUE TITLE
external files: remove from extern removes from view but not from extern list

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#146]
1 - if you remove and then update files the removed file returns to the list

2 - and if you try and reopen a file that was "removed" you get this error:
15:54:37 GideView: cannot add external file: ExtFile not updated: ki.Slice: invalid index: 2 -- len = 2

**Comment by rohrlich** [comment]
I've traced through the delete and it looks fine. The problem seems to be that the files that have been removed are still in the ge.OpenNodes list. So I'm thinking that GideView needs to catch the signals from filetree to know to delete the nodes from the OpenNodes list. What do you think?

**Comment by rcoreilly** [comment]
Yep that sounds right.  Also, it wasn't even deleting from the FileTree ExtFiles list either..  I'll fix this.

**Comment by rcoreilly** [comment]
much better mech now in place with TextBufClosed signal for all cases.
