### ISSUE TITLE
Lookup not finding strings methods

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#156]
for example, doing lookup on HasSuffix in "strings.HasSuffix"

**Comment by rcoreilly** [comment]
I think these are all written in assembly and tucked away in conditionally-compiled files.

**Comment by rohrlich** [comment]
Hmmm, https://golang.org/src/strings/

**Comment by rohrlich** [comment]
This is from the GoLand project tree when you expand Go SDK 1.13
<img width="352" alt="Screen Shot 2020-02-28 at 8 45 56 AM" src="https://user-images.githubusercontent.com/22350787/75567786-f1b9a300-5a06-11ea-8f47-2a656b1acf16.png">

**Comment by rcoreilly** [comment]
it is a bit of a mystery -- strings does define HasPrefix right in strings.go, very simply.  I don't know why it seems uniquely hard to locate -- maybe because there are *other* functions that throw off the parsing?  it DOES capture most of the relevant methods because completion works fine.

**Comment by rcoreilly** [comment]
all top-level func within a package were not registering their Filename and Region -- so completion worked but lookup did not.  fixed now.  updated go parser so cached data will auto-refresh.
