### ISSUE TITLE
Debug - not able to get value of dereferenced variable

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#159]
This may be me not knowing the gide debugger. I've tried follow ptr. If I have code like this:

	for i := 2; i <= *np; i++ {
		var sum float32 = 1.0
		c[i] = math32.Cos(2.0 * math32.Pi * float32(i-1) / float32(n))
		x := (1.0 - c[i]) / 2.0
		y := x

I'd like to see the value of *np. Here is what I see in GoLand, notice value after address.

<img width="481" alt="Screen Shot 2020-03-03 at 6 53 59 PM" src="https://user-images.githubusercontent.com/22350787/75840755-c9240700-5d80-11ea-9bb4-48018eb7894b.png">

**Comment by rcoreilly** [comment]
I tried to look at this case -- it should work!  anyway, looks like some other files are needed:

2020/03/04 00:54:04 open VocalTractEnglishPhones.dat: no such file or directory
bad access
File not found or error opengin file: VocalTractEnglishPhones.dat (open VocalTractEnglishPhones.dat: no such file or directory)2020/03/04 00:54:04 open VocalTractEnglishPhones.dat: no such file or directory

**Comment by rohrlich** [comment]
I checked in the data file so you can run to a breakpoint but there is a crash beyond the example code that I will fix so you might as well wait.

**Comment by rcoreilly** [comment]
what is the status of this one?

**Comment by rohrlich** [comment]
Working
