### ISSUE TITLE
Debugger feature request - Display variables in tree format

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#160]
This may be more than you want to do but maybe some day we can do this.

<img width="497" alt="Screen Shot 2020-03-03 at 7 01 56 PM" src="https://user-images.githubusercontent.com/22350787/75840996-7f87ec00-5d81-11ea-866c-536b06af4cde.png">

**Comment by rcoreilly** [comment]
if you double-click on "ff" you'll get a full tree view of it, in gide.

**Comment by rohrlich** [comment]
Yes, I have been using that feature, not quite as good as getting all of your vars in a single tree but good enough.
