### ISSUE TITLE
Debugger feature request - Disabled breakpoints should look different than enabled

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#161]
Here are a couple of examples:

lighter shade of blue indicates disabled
<img width="529" alt="Screen Shot 2020-03-04 at 9 21 26 AM" src="https://user-images.githubusercontent.com/22350787/75905400-a2ee7d80-5df9-11ea-83d1-457ba1017662.png">

unfilled circle indicates disabled
<img width="455" alt="Screen Shot 2020-03-04 at 9 21 05 AM" src="https://user-images.githubusercontent.com/22350787/75905403-a4b84100-5df9-11ea-859a-1e41ffa82caf.png">

**Comment by rcoreilly** [comment]
now pink vs. red :).  also orange for the current one that stopped the code.
