### ISSUE TITLE
Debugger feature request - execution line colored differently

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#163]
The cursor is in sufficient to show the next line of code that will be executed because you can position the cursor anywhere.

GoLand and Xcode both highlight the entire line with a color and a lot of transparency using a different color than for the line that the cursor is on. I don't use "depth color" so highlighting the entire line would be nice but Gide just marks/colors the narrow number line column so a different color marker in the number line would be fine.

**Comment by rcoreilly** [comment]
will do this one tomorrow -- need to make sure we track where we are properly and clear etc.

**Comment by rcoreilly** [comment]
done
