### ISSUE TITLE
Debugger feature request - Minor - Delete breakpoints from debugger panel

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#164]
With a button for Delete All

**Comment by rcoreilly** [comment]
easy to add the one-by-one delete (except I had to add the signal which was missing).

also not hard to add delete all but does require more overhead -- will do later.

**Comment by rcoreilly** [comment]
not sure we need delete all -- more clutter and a separate toolbar just for that -- calling this good enough & simpler..
