### ISSUE TITLE
Debugger - clearing breakpoint removed marker but not breakpoint

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#167]
breakpoint still visible in breaks panel and runtime did stop

**Comment by rohrlich** [comment]
Clearing the next one worked fine. I'll try to find the circumstance, I have seen this before.

**Comment by rcoreilly** [comment]
still getting this?  some logic has been improved.  I don't see it myself.

**Comment by rohrlich** [comment]
Not seeing is anymore.
