### ISSUE TITLE
Find/Replace for specific file

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#17]
I wanted to do a Replace All in a particular file (with the Find UI). How about adding Find to file context menu and that would imply the particular file. (Did I miss this capability?)

I think this is an example of a wider problem of having 2 editors but no way to specify which to act on or in which to open a file. I've filed a couple of other issues that raise a similar concern.

in both Golang and Xcode cmd-f brings up a find/replace bar at the top of the active editor and you can have one in each editor. There is a separate find bar for project level find.

p.s. Overall the dog food experience is going well.

**Comment by rohrlich** [comment]
I am also using ctrl+s as I am trying to do a combination of emacs and gui to get the full experience (and also to become more facile with emacs style editing).

I see that one view is brighter and that the active file is named in the status bar. I think, however, that the small difference in brightness is not enough of a clue.

**Comment by rcoreilly** [comment]
added Current File Only option to Find..

**Comment by rohrlich** [comment]
Great, now I suggest that "current file only" gets added to the toolbar so that when the tab is displayed you don't need to click on the find button to get the dialog again :)

And maybe the "current file only" flag should be "sticky"

I'll follow your lead and do the same for spelling, all files or current, sound right?

**Comment by rcoreilly** [comment]
yep.  I'll add the extra bits as you suggest.
