### ISSUE TITLE
Debugger - show fields directly on hover

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#170]
for something like someStruct.someField it would be great if hover over the field gave the value directly. Having to hover over the struct instance isn't terrible but the current layout without format is difficult. The actual bug is that the popup window is too small and thus not all field values are visible.

**Comment by rohrlich** [comment]
Could have scrollbar

**Comment by rcoreilly** [comment]
the string value is actually truncated according to params you can see / modify in project prefs -- it is showing the whole thing it has.  Anyway, I was definitely thinking about the hover showing the field too -- that would be nicer.  also note that you can double-click on struct var and it will pull up the tree view.

**Comment by rcoreilly** [comment]
in place -- works for any depth of contiguous paths: obj.Field.Field.Field etc -- and also for double-click -- will only show that part -- nice.
