### ISSUE TITLE
DebugView panic - finding toolbar

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#177]
This is the third time I've seen this panic and I know what I did in this case. And it is reproducable! Debug build was in progress and I closed the Debug tab. The first trace is that case. The second case is similar and I have seen that trace twice but I don't recall the action I took.

rohrlich@MacBook-Pro-5:gide:> ./gide
panic: interface conversion: ki.Ki is nil, not *gi.ToolBar 
goroutine 2035 [running]:
github.com/goki/gide/gide.(*DebugView).ToolBar(...)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/debugview.go:726
github.com/goki/gide/gide.(*DebugView).SetStatus(0xc004980000, 0x3)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/debugview.go:679 +0x32d
github.com/goki/gide/gide.(*DebugView).Start.func1(0xc000000003)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/debugview.go:160 +0x40
github.com/goki/gide/gidebug/gidelve.(*GiDelve).monitorOutput(0xc02b9e2000, 0xc0211602d0, 0x28, 0x30, 0x30, 0x28, 0xc0211602d0)
	/Users/rohrlich/go/src/github.com/goki/gide/gidebug/gidelve/gidelve.go:138 +0x1ef
github.com/goki/gi/giv.(*OutBuf).MonOut(0xc03b18a580)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/outbuf.go:68 +0x5be
created by github.com/goki/gide/gidebug/gidelve.(*GiDelve).Start
	/Users/rohrlich/go/src/github.com/goki/gide/gidebug/gidelve/gidelve.go:115 +0x470

panic: interface conversion: ki.Ki is nil, not *gi.ToolBar
goroutine 111 [running]:
github.com/goki/gide/gide.(*DebugView).ToolBar(...)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/debugview.go:683
github.com/goki/gide/gide.(*DebugView).SetStatus(0xc01054c000, 0x3)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/debugview.go:636 +0x32d
github.com/goki/gide/gide.(*DebugView).Start.func1(0xc000000003)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/debugview.go:154 +0x40
github.com/goki/gide/gidebug/gidelve.(*GiDelve).monitorOutput(0xc01f7e5ce0, 0xc0125b1b30, 0x28, 0x30, 0x30, 0x28, 0xc0125b1b30)
	/Users/rohrlich/go/src/github.com/goki/gide/gidebug/gidelve/gidelve.go:138 +0x1ef
github.com/goki/gi/giv.(*OutBuf).MonOut(0xc010399e80)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/outbuf.go:68 +0x5be
created by github.com/goki/gide/gidebug/gidelve.(*GiDelve).Start
	/Users/rohrlich/go/src/github.com/goki/gide/gidebug/gidelve/gidelve.go:115 +0x470

**Comment by rcoreilly** [comment]
I added guards for these that should prevent this particular crash -- can definitely see how it would arise when building and you close the debugger.  and even tested that it no longer crashes!
