### ISSUE TITLE
Gide frozen when debugging because restart not killing previous executable

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#179]
I didn't reopen because we had cluttered the old ticket with other issues.

Definitely happens sometimes on restart but I haven't narrowed down further.

**Comment by rohrlich** [comment]
Sometimes the running process is killed on restart and other times not. Closing the window (i.e. killing the running debug executable) lets restart continue.

**Comment by rcoreilly** [comment]
hm.. it always kills reliably for me.  Have you updated delve recently?  maybe double check that?

**Comment by rohrlich** [comment]
No, I'll do that.

**Comment by rcoreilly** [comment]
also you can run gide debugger on gide debugger -- I've been doing that a lot lately -- kinda hard to remember which one is which, etc but it does work!  that might be a good way to find the source of this bug if it persists, given that I don't see it.  (or just use GoLand as that would be easier to tell apart!)

**Comment by rohrlich** [comment]
Yes, I'll do that. It is how I resolved the symbols view issues. Give symbols search field a try if you haven't.

**Comment by rcoreilly** [comment]
any update here?

**Comment by rohrlich** [comment]
I just gave the debugger a workout, restarting many times, and it never locked up.
