### ISSUE TITLE
Seeing some drawing above textview in margin 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#18]
Scrolling sometimes leaves bits of the first line of the textview in the space above the textview and below the toolbar.
![screen shot 2018-10-09 at 10 10 37 pm](https://user-images.githubusercontent.com/22350787/46712831-3412f200-cc10-11e8-9fd2-da0bec7f6ff1.png)

**Comment by rcoreilly** [comment]
I'm seeing this -- also on left margin -- will try just making background box slightly bigger..

**Comment by rcoreilly** [comment]
fixed
