### ISSUE TITLE
Add auto-indent to pi lang for specific language one, fix for bracket-type

### ISSUE THREAD

**Issue by rcoreilly** [goki/gide#188]
first, fix the current one so that it deals with brackets properly -- currently doesn't work for `} else {` I think -- maybe others -- test what doesn't work.

then, add that to golang -- will definitely need the lang-specific for python so it makes sense to have that infrastructure in place

**Comment by rcoreilly** [comment]
go-specific: `case` is out-dented.

errors do seem to be specific to } else * { 

have basic fix now..

**Comment by rcoreilly** [comment]
all in place -- very convenient now :)  

@rohrlich  let me know if you like the extra automation or not..

**Comment by rohrlich** [comment]
Great!

- John


On Mar 17, 2020, at 4:34 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:



all in place -- very convenient now :)

@rohrlich<https://github.com/rohrlich> let me know if you like the extra automation or not..
