### ISSUE TITLE
Comment/Uncomment should be toggle

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#19]

**Comment by rcoreilly** [comment]
comment is there: Ctrl-c Ctrl-k I think -- same as emacs :)  would be good if it was a toggle to uncomment though.

**Comment by rohrlich** [comment]
Hmmm, I must be doing something wrong. Also, I don't see it in the keyfuns, would be good to add so mac users could map to cmd+/ which is standard in mac IDEs

**Comment by rohrlich** [comment]
Done - Hopefully covered all of the use cases.
