### ISSUE TITLE
Console issue: Why are numeric values output as links

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#193]
If I print a list of numeric values to the console they are clickable links and if you accidentally click one while trying to copy you lose all the console content and get errors.

**Comment by rcoreilly** [comment]
pi/lex/manual.go: MarkupPathsAsLinks -- pretty quick-n-dirty & could use some more refinement -- since you have a good test case, maybe give it a look?

**Comment by rohrlich** [comment]
That worked. I'll reopen and take a look if I can find a case that breaks it.

**Comment by rcoreilly** [comment]
btw I didn't do anything here -- did you?  it just went away on its own?  did you forget to commit / push?  also this is the same code as #195

**Comment by rohrlich** [comment]
Interesting, I did a diff on your code before I closed the ticket and couldn't find the fix. I was confused by that but the links were gone so I closed it because the links were gone and you mentioned a quick-n-dirty fix. #195 is a different instance so I opened a new ticket! 

And today they are back! I'll take a look.

**Comment by rcoreilly** [comment]
yeah I was just saying that the original code, which I haven't touched (just moved to this new location) is not very well considered and likely could be fixed up.

I think looking for ./ or / at the start might be sufficient -- maybe try that first and see if that works -- we'll probably just need to see how it goes with various use-cases in real-world use to make sure it finds all the relevant links.

**Comment by rohrlich** [comment]
Actually the links were not in the console but in Run Proj (similar). The ./ or / fixes specific problem and also #195.
