### ISSUE TITLE
Crash closing active textview

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#197]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49e0013]

goroutine 435 [running]:
github.com/goki/gi/giv.(*TextBuf).AdjustReg(...)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:1749
github.com/goki/gi/giv.(*TextView).RenderHighlights(0xc05df5ea00, 0x28, 0x28)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:3175 +0xf3
github.com/goki/gi/giv.(*TextView).RenderLines(0xc05df5ea00, 0x28, 0x28, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:3617 +0x4c4
github.com/goki/gi/giv.(*TextView).SelectReset(0xc05df5ea00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:2226 +0xaf
github.com/goki/gi/giv.(*TextView).ResetState(0xc05df5ea00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:311 +0x2f
github.com/goki/gi/giv.(*TextView).SetBuf(0xc05df5ea00, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:334 +0x6e
github.com/goki/gi/giv.TextViewBufSigRecv(0x5226ca0, 0xc05df5ea00, 0x521e060, 0xc01eb6fb00, 0x5, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:441 +0x2c3
github.com/goki/ki/ki.(*Signal).Emit(0xc01eb706e0, 0x521e060, 0xc01eb6fb00, 0x5, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:162 +0x1a5
github.com/goki/gi/giv.(*TextBuf).Close(0xc01eb6fb00, 0xc01b2225a0, 0xc0584b1ba0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:619 +0x482
github.com/goki/gide/gidev.(*GideView).CloseActiveView(0xc05c279500)
	/Users/rohrlich/go/src/github.com/goki/gide/gidev/gideview.go:625 +0xbd
reflect.Value.call(0x4f4f1c0, 0xc05c279500, 0xc613, 0x4f52ece, 0x4, 0x0, 0x0, 0x0, 0x2, 0x4d1bec0, ...)
	/usr/local/go/src/reflect/value.go:460 +0x8ab

**Comment by rcoreilly** [comment]
is this with latest checkin from me?  I think there might be some instability - Kai and I are playing with marbles and got a few issues..

**Comment by rohrlich** [comment]
Yes I believe I updated an hour or so ago.

**Comment by rcoreilly** [comment]
actually that looks like a totally sensible crash!  surprising to not have seen that before!  fixed now.

**Comment by rcoreilly** [comment]
and the other issues with marbles are not dependent on the recent Update change -- just actually "normal" refresh issues..
