### ISSUE TITLE
Feature request - toggle case

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#199]
I'm porting more C++ code and it would be great to have functions to toggle case.

1 - straight upper to lower and vice-versa
2 - force to lower/upper
3 - snake to camel etc.

I bet this code as out there waiting to be grabbed

just access from edit menu, no need for key shortcuts

**Comment by rcoreilly** [comment]
yes we have a package for that already that we're using.  I can easily add to edit menu for selected text.

**Comment by rohrlich** [comment]
great, thanks!

**Comment by rcoreilly** [comment]
https://github.com/iancoleman/strcase

**Comment by rcoreilly** [comment]
done!

**Comment by rohrlich** [comment]
Nice, using now.
