### ISSUE TITLE
"Ignore and Overwrite" needs testing

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#2]
I find that sometimes the auto-save file isn't going away on save and then I get asked about overwrite even thought the file was saved. Other times the file isn't saved and I don't get asked.

Needs testing

**Comment by rohrlich** [comment]
After ignore and overwrite the #backup# version should be deleted.

**Comment by rcoreilly** [comment]
figured out that it was saving during post commands.  should still do remove of existing backup -- didn't check that yet..
