### ISSUE TITLE
Debugger - show values directly in tree view

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#204]
BTW - Some nice enhancements, e.g. hover fixes, thanks.

I'd like the var tree view to show values directly. This is especially important for slices. Clicking on each item is tedious and all of the information is redundant other than the value and the address. Keep the index along with the value.

**Comment by rcoreilly** [comment]
good idea -- easy.

**Comment by rohrlich** [comment]
Great, common in other debuggers so not my idea really :)

**Comment by rcoreilly** [comment]
done!  also good infrastructure fix -- TreeView should have been using Label() method but wasn't.
