### ISSUE TITLE
Completion - receiver not completing correctly

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#205]
Not sure if this should be a reopen of #200 

type Foo struct {
    a float
    b int
}

func (f *Foo) Init() {
    f.<correct completions missing and some that shouldn't be there are appearing>
}

**Comment by rcoreilly** [comment]
yes that would be -- can you provide specific example -- and also double-check that you fully updated (pi too!) as that *should* be fixed.. :)

**Comment by rohrlich** [comment]
hmmm, one particular file is giving me the problem. I'll see if I can figure why. pi was updated.

**Comment by rohrlich** [comment]
I changed the name of the struct and that resolved the issue. Must be defined somewhere else as well. Sorry for the false alarm.
