### ISSUE TITLE
I don't like "find" opening the active file in right frame when already open in left.

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#207]
What is the rationale here? I already have the file open in the left frame and now doing Find I lose what I was looking at in the right frame. 

I think Find should work on whichever frame is the active one and leave my display alone.

**Comment by rcoreilly** [comment]
I thought you suggested it :)  a long time ago.  the logic is that it is easier to follow the replace process if it is next to it.  how about doing a swap, so the same ones are there and it just changes places?

**Comment by rcoreilly** [comment]
note for me: LinkViewFile

**Comment by rcoreilly** [comment]
I just pushed a version that swaps buffers if the target one is on the left, so it preserves the two viewed buffers, so maybe that is less disruptive?

The motivation for having the "link view" always on the right I think is that, per the other issue you just opened, you *cannot* see which one is active if you're not actually "in" that buffer, so when doing Find etc, it is not obvious which one is the active one, so keeping that constant is important.

it would be good to think more about these kinds of issues as the "no tabs" mode is unusual so figuring out how to make it more clear (and functional) would be good.

**Comment by rcoreilly** [comment]
and look back at issue #1 for context :)

**Comment by rohrlich** [comment]
Yes, I bet I did suggest it, LOL. I think, after playing with it for a few minutes that the swap is better. BTW xCode's implementation is what you had before.

Close if you like. I'll keep thinking about these situations.

**Comment by rcoreilly** [comment]
with new text button I think we're good for now..
