### ISSUE TITLE
Interactive replace delayed replace

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#209]
here is an example to explain -- replace x with $ (the cursor is vertical bar in example)

ax
bx
cx

after the first 'y' the text is unchanged

ax
bx|
cx

after the second 'y' the text changes to this

a$
bx
cx|

Note that the cursor is advancing correctly but the replace is one "behind"

**Comment by rohrlich** [comment]
Means the last one isn't actually replaced

**Comment by rcoreilly** [comment]
this is using the textbuf qreplace?

**Comment by rohrlich** [comment]
looks like you committed a fix along with the edit frame  menu button.

**Comment by rcoreilly** [comment]
nope :)

**Comment by rcoreilly** [comment]
I'm assuming you'll re-test and update..  I just did it and it worked fine for me:

a$
b$
c$

**Comment by rohrlich** [comment]
I'm not sure what is happening, test results inconsistent.

**Comment by rohrlich** [comment]
I had a series of lines ending in ;
I did the replace immediately choosing ! to replace all remaining (all of them)
nothing changed
I did a shift undo and the semicolons disappeared

**Comment by rohrlich** [comment]
Now doing ! immediately works, have done it 3 times. I'll see if I can find some patterns for times it fails. In the meantime ignore unless you see a problem yourself.

**Comment by rcoreilly** [comment]
I just experienced it!  I think I know what might have caused it -- will investigate.

**Comment by rcoreilly** [comment]
wow it was seriously broken -- adding a global update start / end in SetStatus I think was the key problem -- currently fixing and testing..

**Comment by rcoreilly** [comment]
global Find/Replace in gide FindView is seriously broken too.  ugh.

**Comment by rcoreilly** [comment]
now working reliably for me with new fixes -- please test and report.

**Comment by rohrlich** [comment]
I've seen it once but that's it.

**Comment by rcoreilly** [comment]
closing for now -- reopen if experience again in any kind of reliable way.
