### ISSUE TITLE
Maybe exclude .gide files from search

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#210]
I got this dialog when doing a Find set to scope "All".

<img width="508" alt="Screen Shot 2020-03-24 at 9 28 13 AM" src="https://user-images.githubusercontent.com/22350787/77451648-2e807c00-6db2-11ea-87e1-6d45d286739a.png">

**Comment by rohrlich** [comment]
It was because the Find history was changed.

**Comment by rcoreilly** [comment]
good idea to exclude -- always bugged me but never filed a ticket.. done.
