### ISSUE TITLE
File Dialog (so really a gi bug) add splitter

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#214]
The directory frame of the open File dialog doesn't let me see full names. There is a scroll bar that is of no use because it moves the frame. Suggest removing scroll and adding splitter between directory and file name frames.

**Comment by rcoreilly** [comment]
not sure what you mean by "directory frame" -- the "favorites" on the left?  

the Name field in the main list of files should auto-size to contents..

**Comment by rohrlich** [comment]
yeah the favorites, sorry :)

**Comment by rcoreilly** [comment]
ok -- could do that -- was hoping to avoid extra complexity and encourage users to use brief names there as these are high-freq ones -- you can edit them in gogi prefs to use shorter names..

**Comment by rohrlich** [comment]
It is minor, didn't know you could alias them.

**Comment by rcoreilly** [comment]
btw it is a good idea to file these kinds of issues here rather than in gi --gi should have all the core infrastructure bugs and we can use gide for more of the end-user usability issues, even if they would be more properly in gi code-wise.

**Comment by rcoreilly** [comment]
assuming we're ok with this at this point? having a splitter would require saving it etc.
