### ISSUE TITLE
Error: no specific support for language -- repeatedly output to console

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#215]
Editing a file of unsupported type (e.g. json) generates a lot of console messages from the code below. One of the callers is TextBuf.AutoIndent but there are others.

func (ll *LangSupporter) Props(sup filecat.Supported) (*LangProps, error) {
	lp, has := StdLangProps[sup]
	if !has {
		err := fmt.Errorf("pi.LangSupport.Props: no specific support for language: %v", sup)
		//		log.Println(err.Error()) // don't want output
		return nil, err
	}
	return lp, nil
}

**Comment by rcoreilly** [comment]
checked in fix.
