### ISSUE TITLE
Find with location "All" looks in directories that are closed if they were previously opened 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#216]
Perhaps a little picky :) but also a bit confusing and I mention it because it might mean that some opened/closed bit is not being set when directories are closed.

**Comment by rohrlich** [comment]
BTW gide has been very stable and functional and I am giving it a good workout!

**Comment by rcoreilly** [comment]
that was kinda serious actually: ki.Ki was not properly responding to the "return false" case on FuncDownMeFirst!

**Comment by rcoreilly** [comment]
tested pretty extensively by now -- seems like it is working -- reopen if not!
