### ISSUE TITLE
Panic editing imports - 100% reproducible

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#217]
Go to any files imports and after the last import add a new line and enter a quote char

panic: runtime error: slice bounds out of range [1:0]

goroutine 380 [running]:
github.com/goki/pi/langs/golang.(*GoLang).ImportPathPkg(0x6393e58, 0xc014723a0c, 0x1, 0x42b7380000000000, 0x40f9800000000000, 0x41708000, 0x0, 0x524d780, 0xc003fe4000)
	/Users/rohrlich/go/src/github.com/goki/pi/langs/golang/parsedir.go:302 +0xf8
github.com/goki/pi/langs/golang.(*GoLang).AddImportToExts(0x6393e58, 0xc003d021f0, 0xc014723a0c, 0x1, 0x6393e01)
	/Users/rohrlich/go/src/github.com/goki/pi/langs/golang/parsedir.go:352 +0x49
created by github.com/goki/pi/langs/golang.(*GoLang).AddImportsToExts
	/Users/rohrlich/go/src/github.com/goki/pi/langs/golang/parsedir.go:339 +0x1a2

**Comment by rohrlich** [comment]
Actually the " can be at start etc. as it is about the count of imports.

Opening the file will also cause panic so edit outside of gide and reopen.

**Comment by rcoreilly** [comment]
easy fix..
