### ISSUE TITLE
horizontal scroll of textview not updating correctly (sometimes)

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#223]
I don't notice the problem shown in the figure if I use the scrollbar but with a 2 finger scroll on mac and then a click in the text area I get this.

![Screen Shot 2020-04-06 at 6 57 19 PM](https://user-images.githubusercontent.com/22350787/78622040-f1e46400-7838-11ea-9584-a35764c8a068.png)

**Comment by rcoreilly** [comment]
I think this should be fixed with latest checkin -- let me know

**Comment by rohrlich** [comment]
Yes fixed.
