### ISSUE TITLE
Don't evaluate if debug not running

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#227]
If you start debug but the code has errors AND you happen to hover over a variable you can get a nil deference  (dv.Dbg can be nil) Full stack below.

func (dv *DebugView) VarValue(varNm string) string {
	if strings.Contains(varNm, ".") {
		vv, err := dv.Dbg.GetVar(varNm, dv.State.CurTask, dv.State.CurFrame)
...
}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x4c2cf4d]

goroutine 286 [running]:
github.com/goki/gide/gide.(*DebugView).VarValue(0xc03ab8cd00, 0xc02248bba0, 0xb, 0xc02248bba0, 0xb)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/debugview.go:667 +0x6d
github.com/goki/gide/gide.(*TextView).DebugVarValueAtPos(0xc00396f500, 0x1f2, 0x2aa, 0x52e6ce0, 0xc00396f500)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/textview.go:167 +0x189
github.com/goki/gide/gide.(*TextView).HoverEvent.func1(0x52e6ce0, 0xc00396f500, 0x52d03a0, 0xc0006c9000, 0x5, 0x4ee2fe0, 0xc017d829c0)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/textview.go:232 +0x109
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc005629eb0, 0x52d03a0, 0xc0006c9000, 0x5, 0x4ee2fe0, 0xc017d829c0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc0006c9190, 0x52623a0, 0xc017d829c0, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:237 +0x54f
github.com/goki/gi/gi.(*EventMgr).SendHoverEvent(0xc0006c9190, 0xc0145c1140)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:638 +0xcb
github.com/goki/gi/gi.(*EventMgr).MouseMoveEvents.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:511 +0x99
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x44

**Comment by rcoreilly** [comment]
added nil guard
