### ISSUE TITLE
Would be convenient to have lookup on context menu

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#228]

**Comment by rcoreilly** [comment]
good idea!  done.

**Comment by rohrlich** [comment]
Not seeing it on context menu, do you?

**Comment by rcoreilly** [comment]
![Screen Shot 2020-04-30 at 3 42 49 PM](https://user-images.githubusercontent.com/9605819/80766029-4d80d500-8af9-11ea-8341-9522e5e4ea9c.png)

**Comment by rohrlich** [comment]
Sorry!!! Thought I was fully up to date. I am now.
