### ISSUE TITLE
Find: results from ignore case display result in lower case

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#23]
Results should be the actual text with case, not the lowered cased version used for "ignore case"

If I search case sensitive I get:

gide.go: 2
	gide.go: ge.FindOrMakeMainTab(&#34;Spell&#34;, KiT_SpellView, true) // sel
	gide.go: 	fv := fvi.Embed(KiT_SpellView).(*SpellView)

spellingview.go: 1
	spellingview.go: var KiT_SpellView = kit.Types.AddType(&amp;SpellVie

--------------------------------------
If I search case insensitive I get:

e.go: ge.findormakemaintab(&#34;spell&#34;, kit_spellview, true) // sel
	gide.go: 	fv := fvi.embed(kit_spellview).(*spellview)

spellingview.go: 1
	spellingview.go: var kit_spellview = kit.types.addtype(&amp;spellvie

**Comment by rcoreilly** [comment]
fixed..
