### ISSUE TITLE
Panic moving mouse if window scrollable and you close all tabs 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#235]
There are multiple ways to get his crash. Here is one
- Open a project with all panels (nav, 2 edit, tab)
- Shrink horizontally to get main window scrollbar
- Close the console tab (the only one there on first opening project)

panic: runtime error: index out of range [0] with length 0

goroutine 40 [running]:
github.com/goki/ki/ki.(*Node).Child(...)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/node.go:588
github.com/goki/gi/gi.(*Layout).Move2DChildren(0xc000440100, 0xffffffffffffff5e, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1441 +0x223
github.com/goki/gi/gi.(*Layout).Move2D(0xc000440100, 0xffffffffffffff5e, 0x0, 0x2db, 0x41, 0x336, 0x507)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:2069 +0x119
github.com/goki/gi/gi.(*Node2DBase).Move2DChildren(0xc003a2e000, 0xffffffffffffff5e, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:865 +0x159
github.com/goki/gi/gi.(*WidgetBase).Move2D(0xc003a2e000, 0xffffffffffffff5e, 0x0, 0x4, 0x40, 0x337, 0x508)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:438 +0x8f
github.com/goki/gi/gi.(*WidgetBase).ReRender2DTree(0xc003a2e000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:424 +0x2dd
github.com/goki/gi/gi.(*Viewport2D).ReRender2DAnchor(0xc00068ea80, 0x12e12240, 0xc003a2e000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:396 +0xc6
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes(0xc00068ea80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:828 +0x276
github.com/goki/gi/gi.(*Viewport2D).NodeUpdated(0xc00068ea80, 0x12e12240, 0xc003a2e000, 0x1, 0x4d98580, 0xc009a95060)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:725 +0x166
github.com/goki/gi/gi.SignalViewport2D(0x52dd520, 0xc00068ea80, 0x52dc860, 0xc003a2e000, 0x1, 0x4d98580, 0xc009a95060)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:679 +0x134
github.com/goki/ki/ki.(*Signal).Emit(0xc003a2e058, 0x52dc860, 0xc003a2e000, 0x1, 0x4d98580, 0xc009a95060)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:162 +0x1a5
github.com/goki/ki/ki.(*Node).UpdateEnd(0xc003a2e000, 0x1)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/node.go:1914 +0x20a
github.com/goki/gi/gi.(*TabView).DeleteTabIndex(0xc003a2e000, 0x0, 0xc000663a01, 0x4771372, 0xc003a2e000, 0x5299ea0, 0x4ee3a20, 0x52dc860)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/tabview.go:336 +0x220
github.com/goki/gi/gi.(*TabView).DeleteTabIndexAction(0xc003a2e000, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/tabview.go:348 +0x3e
github.com/goki/gi/gi.(*TabButton).ConfigPartsDeleteButton.func1(0x52dc420, 0xc003a5c000, 0x52d4d20, 0xc003ae6600, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/tabview.go:636 +0xd8
github.com/goki/ki/ki.(*Signal).Emit(0xc003ae7ea8, 0x52d4d20, 0xc003ae6600, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:162 +0x1a5
github.com/goki/gi/gi.(*Action).ButtonRelease(0xc003ae6600)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/action.go:222 +0x113
github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1(0x52d4d20, 0xc003ae6600, 0x52ddda0, 0xc00066f000, 0x0, 0x4eeeac0, 0xc0008083c0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:438 +0xcd
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc000663d88, 0x52ddda0, 0xc00066f000, 0x0, 0x4eeeac0, 0xc0008083c0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc00066f190, 0x526fca0, 0xc0008083c0, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:237 +0x54f
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc00066f000, 0x526fca0, 0xc0008083c0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1521 +0x7ac
github.com/goki/gi/gi.(*Window).EventLoop(0xc00066f000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1448 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:863 +0xa6

**Comment by rcoreilly** [comment]
fixed with ChildTry instead of Child in layout.
