### ISSUE TITLE
Panic clicking on SaveAs

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#238]
panic: interface conversion: interface {} is giv.FileTime, not time.Time

goroutine 11 [running]:
github.com/goki/gi/giv.(*TimeValueView).UpdateWidget(0xc0540c6820)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/basicviews.go:1057 +0x13d
github.com/goki/gi/giv.(*TimeValueView).ConfigWidget(0xc0540c6820, 0x530bfc0, 0xc06635d500)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/basicviews.go:1084 +0x337
github.com/goki/gi/giv.(*TableView).ConfigSliceGrid(0xc054012800)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:377 +0x1bd5
github.com/goki/gi/giv.(*TableView).Config(0xc054012800)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:188 +0x287
github.com/goki/gi/giv.(*FileView).UpdateFiles(0xc03b615800)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/fileview.go:525 +0x71b
github.com/goki/gi/giv.(*FileView).Config(0xc03b615800)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/fileview.go:209 +0x343
github.com/goki/gi/giv.(*FileView).SetFilename(0xc03b615800, 0xc003ea9e40, 0x3b, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/fileview.go:82 +0xab
github.com/goki/gi/giv.FileViewDialog(0xc000684a80, 0xc003ea9e40, 0x3b, 0x0, 0x0, 0x4ffbe52, 0x9, 0x5064860, 0x2c, 0x0, ...)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/dialogs.go:492 +0x22b
github.com/goki/gi/giv.(*FileValueView).Activate(0xc03e827860, 0xc000684a80, 0x52e0d80, 0xc03e827860, 0xc054a38ed0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/filevalueview.go:68 +0x2b7
github.com/goki/gi/giv.MethViewCall(0x52d9f00, 0xc000684a80, 0x52d1700, 0xc003fb1300, 0x0, 0x4e0d680, 0xc003e8de60)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/methview.go:689 +0x45d
github.com/goki/ki/ki.(*Signal).Emit(0xc003fb2ba8, 0x52d1700, 0xc003fb1300, 0x0, 0x4e0d680, 0xc003e8de60)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:162 +0x1a5
github.com/goki/gi/gi.(*Action).ButtonRelease(0xc003fb1300)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/action.go:222 +0x113

**Comment by rohrlich** [comment]
I reopened the file, selected Open Autosave File, found the change and did A <-- B and clicked Save.

Same crash (i.e. same stack)

**Comment by rcoreilly** [comment]
oops -- didn't rebuild gide and thus didn't get the testing -- easy fix. :)

**Comment by rcoreilly** [comment]
fixed now
