### ISSUE TITLE
Save Project: Does it save files?

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#24]
If Save Project calls save on each of the unsaved files then the bug is that after Save Project closing the window still displays the message that N files are open.

I expect most users would assume that Save Project also saves the files in the project.

**Comment by rohrlich** [comment]
Looking at the code it seems that only project settings are saved. Maybe add a menu item "Save All Files" to suggest files and project are saved independently.

**Comment by rcoreilly** [comment]
added a prompt to save all files if files are unsaved.  could make it automatic but prompt is easy and more explicit..
