### ISSUE TITLE
Panic opening file chooser

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#240]
Launch gide
New Project
Click on "Click to open file chooser"

panic: interface conversion: interface {} is giv.FileTime, not time.Time

goroutine 38 [running]:
github.com/goki/gi/giv.(*TimeValueView).UpdateWidget(0xc0088a8d00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/basicviews.go:1057 +0x13d
github.com/goki/gi/giv.(*TimeValueView).ConfigWidget(0xc0088a8d00, 0x5267fc0, 0xc008968a00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/basicviews.go:1084 +0x337
github.com/goki/gi/giv.(*TableView).ConfigSliceGrid(0xc0083e2000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:377 +0x1bbb
github.com/goki/gi/giv.(*TableView).Config(0xc0083e2000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:188 +0x287
github.com/goki/gi/giv.(*FileView).UpdateFiles(0xc0069f6600)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/fileview.go:525 +0x758
github.com/goki/gi/giv.(*FileView).Config(0xc0069f6600)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/fileview.go:209 +0x343
github.com/goki/gi/giv.(*FileView).SetFilename(0xc0069f6600, 0x0, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/fileview.go:82 +0xab
github.com/goki/gi/giv.FileViewDialog(0xc0069cea80, 0x0, 0x0, 0x0, 0x0, 0x4fa7d31, 0xd, 0x0, 0x0, 0x0, ...)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/dialogs.go:492 +0x22b
github.com/goki/gi/giv.(*FileValueView).Activate(0xc00043fa00, 0xc0069cea80, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/filevalueview.go:68 +0x2b7
github.com/goki/gi/giv.(*FileValueView).ConfigWidget.func1(0x523cd80, 0xc00043fa00, 0x522d700, 0xc0069e4c80, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/filevalueview.go:52 +0xa6

**Comment by rcoreilly** [comment]
u already filed this and and I already fixed it! :)  update gi

**Comment by rohrlich** [comment]
I had forgotten to rebuild!
