### ISSUE TITLE
Crash opening GoGi prefs

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#25]
Johns-Mac-Pro:~/go/src/github.com/goki/gide/cmd/gide $ ./gide
Effective LogicalDPI now: 78  PhysicalDPI: 109  Eff LogicalDPIScale: 0.7155963  ZoomFactor: 1.0833334
Effective LogicalDPI now: 84  PhysicalDPI: 109  Eff LogicalDPIScale: 0.7706422  ZoomFactor: 1.1666666
Preferences Saved to prefs.json
2018-10-11 07:59:10.701 gide[67992:4991792] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '_installCarbonMenuEventHandlers called with existing _menuEventHandler already associated with menu for menu <NSMenu: 0xb43b4d0>
	Title: gide
	Open bounds: [t=-6.86734e+218, l=7.85138e-313, b=-6.86734e+218, r=6.96414e+252]
	Supermenu: 0xb41c1d0 (), autoenable: NO
	Items:     (
        "<NSMenuItem: 0xb420ee0 About gide>",
        "<NSMenuItem: 0xb44e160 GoGi Preferences...>",
        "<NSMenuItem: 0xb44d790 Gide Preferences...>",
        "<NSMenuItem: 0xb43a950 >",
        "<NSMenuItem: 0xb41f290 Quit>"
    )'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff56d3f66b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7df81942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff56dcf955 +[NSException raise:format:] + 197
	3   AppKit                              0x00007fff54243e39 -[NSCarbonMenuImpl _installCarbonMenuEventHandlers] + 99
	4   AppKit                              0x00007fff54243367 -[NSCarbonMenuImpl _instantiateCarbonMenu] + 1240
	5   AppKit                              0x00007fff5424546f -[NSCarbonMenuImpl _principalMenuRefCreateIfNecessary] + 42
	6   AppKit                              0x00007fff545ba804 -[NSCarbonMenuImpl _itemLostMagicAppleMenuStatus:] + 87
	7   AppKit                              0x00007fff546dadc4 -[NSCarbonMenuImpl _menuLostMainMenuStatus] + 137
	8   AppKit                              0x00007fff5421812f -[NSMenu _setMenuName:] + 384
	9   AppKit                              0x00007fff54220f02 -[NSApplication setMainMenu:] + 360
	10  AppKit                              0x00007fff5421838a -[NSMenu _setMenuName:] + 987
	11  gide                                0x0000000004760415 -[ScreenGLView windowDidBecomeKey:] + 53
	12  CoreFoundation                      0x00007fff56cd05cc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	13  CoreFoundation                      0x00007fff56cd049a _CFXRegistrationPost + 458
	14  CoreFoundation                      0x00007fff56cd01d1 ___CFXNotificationPost_block_invoke + 225
	15  CoreFoundation                      0x00007fff56c8ed22 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	16  CoreFoundation                      0x00007fff56c8ddb3 _CFXNotificationPost + 659
	17  Foundation                          0x00007fff58db78c7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	18  AppKit                              0x00007fff5436e973 -[NSWindow becomeKeyWindow] + 1488
	19  AppKit                              0x00007fff5436dbcd -[NSWindow _changeKeyAndMainLimitedOK:] + 878
	20  AppKit                              0x00007fff5441b27e -[NSWindow _makeKeyRegardlessOfVisibility] + 108
	21  AppKit                              0x00007fff54370c0c NSPerformVisuallyAtomicChange + 146
	22  AppKit                              0x00007fff5441b1b5 -[NSWindow makeKeyAndOrderFront:] + 90
	23  libdispatch.dylib                   0x00007fff7eb665fa _dispatch_call_block_and_release + 12
	24  libdispatch.dylib                   0x00007fff7eb5edb8 _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x00007fff7eb6a395 _dispatch_main_queue_callback_4CF + 1148
	26  CoreFoundation                      0x00007fff56cf8e59 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	27  CoreFoundation                      0x00007fff56cbb66a __CFRunLoopRun + 2586
	28  CoreFoundation                      0x00007fff56cba9b7 CFRunLoopRunSpecific + 487
	29  HIToolbox                           0x00007fff55f9ad96 RunCurrentEventLoopInMode + 286
	30  HIToolbox                           0x00007fff55f9ab06 ReceiveNextEventCommon + 613
	31  HIToolbox                           0x00007fff55f9a884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	32  AppKit                              0x00007fff5424ba73 _DPSNextEvent + 2085
	33  AppKit                              0x00007fff549e1e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	34  AppKit                              0x00007fff54240885 -[NSApplication run] + 764
	35  gide                                0x000000000405a620 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff7ece8b66 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x475f930, 0xc000061ec8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000061e98 sp=0xc000061e60 pc=0x400513e
github.com/goki/gi/oswin/driver/macdriver._Cfunc_startDriver()
	_cgo_gotypes.go:688 +0x41 fp=0xc000061ec8 sp=0xc000061e98 pc=0x468a121
github.com/goki/gi/oswin/driver/macdriver.startDriver()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:102 +0x3b fp=0xc000061f20 sp=0xc000061ec8 pc=0x468b05b
github.com/goki/gi/oswin/driver/macdriver.Main(0xc00036ddb0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/macdriver.go:27 +0x35 fp=0xc000061f30 sp=0xc000061f20 pc=0x4685755
github.com/goki/gi/oswin/driver.main(0xc00036ddb0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver_darwin.go:20 +0x2b fp=0xc000061f48 sp=0xc000061f30 pc=0x46906eb
github.com/goki/gi/oswin/driver.Main(0xc00036ddb0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b fp=0xc000061f60 sp=0xc000061f48 pc=0x46906ab
github.com/goki/gi/gimain.Main(0x4980ee8)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:24 +0x57 fp=0xc000061f80 sp=0xc000061f60 pc=0x4707b27
main.main()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:20 +0x2d fp=0xc000061f98 sp=0xc000061f80 pc=0x475e03d
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000061fe0 sp=0xc000061f98 pc=0x402f057
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000061fe8 sp=0xc000061fe0 pc=0x405ae81

goroutine 10 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0x5605d80)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0x5605d78)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:81 +0x1c2
main.main.func1()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:21 +0x20
github.com/goki/gi/gimain.Main.func1(0x4ae5860, 0x55bfa20)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:25 +0x24
github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:185 +0x40
created by github.com/goki/gi/oswin/driver/macdriver.driverStarted
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:184 +0x5f

goroutine 22 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc000001980, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:233 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:175 +0xe8

goroutine 23 [runnable]:
golang.org/x/mobile/gl.(*context).enqueue(0xc0002ed8c0, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/rohrlich/go/src/golang.org/x/mobile/gl/work.go:110 +0xd9
golang.org/x/mobile/gl.(*context).Flush(0xc0002ed8c0)
	/Users/rohrlich/go/src/golang.org/x/mobile/gl/gl.go:580 +0x5c
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).Publish(0xc000001980, 0x13)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:367 +0x5d
github.com/goki/gi.(*Window).Publish(0xc000150f00)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:754 +0x225
github.com/goki/gi.SignalWindowPublish(0x4b16c20, 0xc000150f00, 0x4b16c20, 0xc000150f00, 0x1, 0x47bf220, 0xc00d1de408)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:767 +0x93
github.com/goki/ki.(*Signal).Emit(0xc000150f58, 0x4b16c20, 0xc000150f00, 0x1, 0x47bf220, 0xc00d1de408)
	/Users/rohrlich/go/src/github.com/goki/ki/signal.go:157 +0x1b9
github.com/goki/ki.(*Node).UpdateEnd(0xc000150f00, 0x4b16c01)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1118 +0x147
github.com/goki/gi.(*Window).GenMouseFocusEvents(0xc000150f00, 0xc0094506c0, 0xc009450601, 0x296b3d01)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1616 +0x251
github.com/goki/gi.(*Window).EventLoop(0xc000150f00)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1299 +0xeaf
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:542 +0x66

goroutine 55 [chan receive]:
github.com/goki/gi/giv.TextViewBlink()
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:2060 +0x46
created by github.com/goki/gi/giv.(*TextView).StartCursor
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:2094 +0xf3

goroutine 101 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc000000f00, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:233 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:175 +0xe8

goroutine 102 [runnable]:
image/color.(*NRGBA).RGBA(0xc00d21fe1c, 0xe, 0x4abac40)
	<autogenerated>:1 +0x82
github.com/srwiley/scanFT.(*RGBAColFuncPainter).Paint(0xc00c9aac90, 0xc00c89d298, 0x3e, 0x40, 0x1, 0x0, 0x0, 0x53b, 0x1f)
	/Users/rohrlich/go/src/github.com/srwiley/scanFT/scan.go:529 +0x228
github.com/srwiley/scanFT.(*ScannerFT).Draw(0xc00c89b000)
	/Users/rohrlich/go/src/github.com/srwiley/scanFT/scan.go:428 +0x3de
github.com/goki/gi.(*Paint).fill(0xc00c624eb0, 0xc00c624eb0)
	/Users/rohrlich/go/src/github.com/goki/gi/paint.go:567 +0x24a
github.com/goki/gi.(*Paint).FillPreserve(0xc00c624eb0, 0xc00c624eb0)
	/Users/rohrlich/go/src/github.com/goki/gi/paint.go:591 +0x35
github.com/goki/gi.(*Paint).Fill(0xc00c624eb0, 0xc00c624eb0)
	/Users/rohrlich/go/src/github.com/goki/gi/paint.go:597 +0x35
github.com/goki/gi.(*Paint).FillBox(0xc00c624eb0, 0xc00c624eb0, 0x0, 0x41f8000044a76000, 0xc000669660)
	/Users/rohrlich/go/src/github.com/goki/gi/paint.go:610 +0x115
github.com/goki/gi.(*MenuBar).MenuBarStdRender(0xc000669400)
	/Users/rohrlich/go/src/github.com/goki/gi/bars.go:48 +0x99
github.com/goki/gi.(*MenuBar).Render2D(0xc000669400)
	/Users/rohrlich/go/src/github.com/goki/gi/bars.go:82 +0x69
github.com/goki/gi.(*Layout).Render2DChildren(0xc000668000)
	/Users/rohrlich/go/src/github.com/goki/gi/layout.go:1277 +0x111
github.com/goki/gi.(*Layout).Render2D(0xc000668000)
	/Users/rohrlich/go/src/github.com/goki/gi/layout.go:1837 +0xc1
github.com/goki/gi.(*Node2DBase).Render2DChildren(0xc00c624a80)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:630 +0xa2
github.com/goki/gi.(*Viewport2D).Render2D(0xc00c624a80)
	/Users/rohrlich/go/src/github.com/goki/gi/viewport2d.go:437 +0x6d
github.com/goki/gi.(*Node2DBase).Render2DTree(0xc00c624a80)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:591 +0x8e
github.com/goki/gi.(*Node2DBase).FullRender2DTree(0xc00c624a80)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:483 +0x89
github.com/goki/gi.(*Viewport2D).FullRender2DTree(0xc00c624a80)
	/Users/rohrlich/go/src/github.com/goki/gi/viewport2d.go:374 +0x91
github.com/goki/gi.(*Window).FullReRender(0xc00069b900)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:603 +0x4f
github.com/goki/gi.(*Window).EventLoop(0xc00069b900)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1244 +0x77d
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:542 +0x66

**Comment by rcoreilly** [comment]
I assume you're on very latest??  I tried to prevent this but now looking at this stack I think I see what could be the problem -- will give another try.

**Comment by rohrlich** [comment]
Yep, latest.

**Comment by rcoreilly** [comment]
filed ticket in gi

**Comment by rcoreilly** [comment]
have ticket 156 in gi on this now, with updates on what I've tried..
