### ISSUE TITLE
Result of "Find" hard to read

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#250]
I experience the result of a "Find" very difficult to read, largely because of the unaligned text. I suggest we left align the context string and right align the location url as GoLand does. See figs.

And for a within file search just show the name of the file rather than the fuller path.

![Screen Shot 2020-05-21 at 9 48 40 AM](https://user-images.githubusercontent.com/22350787/82583960-a7991700-9b48-11ea-87e6-19cd7e9c9beb.png)
![Screen Shot 2020-05-21 at 9 49 02 AM](https://user-images.githubusercontent.com/22350787/82583978-ae278e80-9b48-11ea-9c24-c52eb838e456.png)

**Comment by rohrlich** [comment]
Especially hard to read when the lines wrap so we might want to consider solutions for that, there are a few.

**Comment by rcoreilly** [comment]
good suggestion -- this should be easy.  although we do have a general convention that the link is first on the left, as in compile errs etc, so I would prefer to just keep that, so really just aligning the find text.

**Comment by rohrlich** [comment]
That should be really easy, just trim.

**Comment by rcoreilly** [comment]
see how it looks now.. tab + trim
