### ISSUE TITLE
Would like commands (Git Commit) to scope to select directory

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#260]
If I use the context menu and select "Exec Cmd" and choose, for example, "git commit" the commit should scope to the files in the selected directory. Otherwise I need to select files individually to narrow scope. Of course I can go to the command line to handle but I think it is misleading anyway to not scope commands.

**Comment by rcoreilly** [comment]
It does scope all commands to the selected file or directory.  If you look at the commands, they have the {} variables that get filled in based on the current active file.  In the case of commit, git treats the entire repository as a monolithic thing by default -- so even if you're in a subdirectory, it does the whole thing.  Maybe there are some special args to override that but the default is to operate on the repository as a whole.  If you want that special version, it is easy to add it with appropriate args as a new command.

**Comment by rohrlich** [comment]
I looked at the git command options and don't see one that narrows scope. Goland does it so I'm use to it and it is handy. I suppose they just look for the modified files in the directory and build the command. Not important.
