### ISSUE TITLE
Canceling "Run Prompt" dialog causes crash

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#262]
github.com/goki/gide/gide.(*CmdAndArgs).PrepCmd(0xc0006cdea0, 0xc000799ce8, 0x0, 0x0, 0xc00047b9f8)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/commands.go:110 +0x468
github.com/goki/gide/gide.(*Command).RunBuf(0xc00073ef60, 0x5351760, 0xc000799500, 0xc00c118000, 0xc0006cdea0, 0xc01e6b66c0)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/commands.go:380 +0x5a
created by github.com/goki/gide/gide.(*Command).RunAfterPrompts
	/Users/rohrlich/go/src/github.com/goki/gide/gide/commands.go:361 +0x3e1

**Comment by rcoreilly** [comment]
haven't seen -- likely fixed
