### ISSUE TITLE
Copy shortcut incorrect in main tab frame

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#27]
![screen shot 2018-10-11 at 8 37 41 am](https://user-images.githubusercontent.com/22350787/46812045-26a15900-cd31-11e8-9ae6-106bd1e48b2e.png)

**Comment by rcoreilly** [comment]
Actually that is correct!  there are multiple different shortcuts and that's one of them. Alt+W I think. due to random nature of map ordering, it chooses them at random..
