### ISSUE TITLE
panic on arch arm64 linux

### ISSUE THREAD

**Issue by ddkwork** [goki/gide#295]
![Screenshot_20221130_080851_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/204675890-d2058adb-c396-4cce-bb8f-7e01f3bc9b61.jpg)

**Comment by rcoreilly** [comment]
looks like vulkan is not finding a compatible driver.  can you look at various vulkan debugging utilities? (just google it).  I think our impl is missing the proper logic to find the best driver.

**Comment by ddkwork** [comment]
> looks like vulkan is not finding a compatible driver. can you look at various vulkan debugging utilities? (just google it). I think our impl is missing the proper logic to find the best driver.

how todo， but gio ui was working

![Screenshot_20221130_124232_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/204709301-4460e1a6-bfe3-46f1-a8c2-a3c110e61e78.jpg)

**Comment by rcoreilly** [comment]
can you paste the output of `vulkaninfo` ?

**Comment by ddkwork** [comment]
> can you paste the output of vulkaninfo ?

what command i should input？

**Comment by rcoreilly** [comment]
type vulkaninfo on the terminal

**Comment by ddkwork** [comment]
> type vulkaninfo on the terminal

![Screenshot_20221201_150327_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/204987251-3c644501-9cf9-45ca-9bd9-f885b0b571d7.jpg)

**Comment by rcoreilly** [comment]
just "vulcaninfo", no quotes..

**Comment by ddkwork** [comment]
> just "vulcaninfo", no quotes..

![Screenshot_20221201_205054_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/205057423-458c0c45-1f04-4f7e-bb4e-6eb6032468c4.jpg)

no bin
