### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#30]
The "gocode" code doesn't get built when gide is built. To get completion working you need have the environment variable GOBIN set to your go/bin directory AND you need to go to go/src/github.com/mdempsky/gocode and build with the following command

go install

which will put the gocode binary into go/bin

do not use "go build gocode.go" or go install gocode.go" - neither will work

**Comment by rohrlich** [comment]
Will not be an issue moving to our own parser

**Comment by rcoreilly** [comment]
now have GoPi :)
