### ISSUE TITLE
Crash opening file - reproducible

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#31]
This has happened maybe 3 times but I didn't report earlier as I don't know how to reproduce yet.

runtime.fatalpanic at panic.go:681
runtime.gopanic at panic.go:556
runtime.panicindex at panic.go:44
github.com/goki/gide.(*Gide).ViewFileNode at gide.go:562
github.com/goki/gide.(*Gide).NextViewFileNode at gide.go:583
github.com/goki/gide.(*Gide).FileNodeOpened at gide.go:1872
github.com/goki/gide.(*Gide).ConfigSplitView.func1 at gide.go:1788
github.com/goki/ki.(*Signal).Emit at signal.go:157
github.com/goki/gi/giv.(*TreeView).Open at treeview.go:677
github.com/goki/gi/giv.(*TreeView).ToggleClose at treeview.go:685
github.com/goki/gi/giv.(*TreeView).TreeViewEvents.func5 at treeview.go:1340
github.com/goki/gi.(*WinEventRecv).Call at window.go:1423
github.com/goki/gi.(*Window).SendEventSignal at window.go:1544
github.com/goki/gi.(*Window).EventLoop at window.go:1297
runtime.goexit at asm_amd64.s:1333

**Comment by rcoreilly** [comment]
yep easy fix there

**Comment by rohrlich** [comment]
Just fixed it myself and found yours when I tried to push!
