### ISSUE TITLE
Minor Issue with "Splits" editing

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#34]
* For splits **specifically** might be better to remove +/- and just have 5 labeled elements. 

• There is a limit of 1 + 2 + 2 panels but you can keep adding useless fields to the slice.
-- Disable "+" when limit is reached (disable minus if minimum is reached)
-- Would be useful to put min/max on slice increment generally as I bet there are other cases

**Comment by rcoreilly** [comment]
all done
