### ISSUE TITLE
Clicking link in findview always opens text in right view if 2 views are open

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#36]
Suggest for "Find" (which by the way works wonderfully!) that displaying of found items (by clicking on link) always open the file in the right side textview if two are open. The use case that comes to mind is having code I'm editing in the left view and using the right view to find something relevant that I need for the code I'm editing.

**Comment by rcoreilly** [comment]
um... this is what I JUST implemented last night based on your earlier comment to the same effect.. :)

**Comment by rcoreilly** [comment]
I like current "right side" behavior.
