### ISSUE TITLE
Add single instance replace to Find/Replace tab

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#38]
It seems that from the find/replace dialog the only replace option is "All". Would like to be able to click the up/down arrows and replace current item.

**Comment by rcoreilly** [comment]
replace is a button that just does the current one!  i'll add an icon to make that more obvious.

**Comment by rohrlich** [comment]
Yeah, users!

But joking aside I think we need to have a clear distinction between buttons and labels. I see that Find: which looks like a button is both button and label while replace just looks like a label and is both. Is that because Find: is activated by Enter/Return?

Maybe make Replace: a label and have a button to left of "All" which says "Replace" and make both look like buttons. Seems very unusual to have plain text be a button

**Comment by rcoreilly** [comment]
fixed with new thin outlines on all toolbar buttons.
