### ISSUE TITLE
Comment-Out not working

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#39]
Brief glimpse of code shows you need to have a selection, is that how it works in emacs?

Any IDE I've used does comment/uncomment on whatever line the cursor is on. I can see where the region version might be useful but would be best if it could comment whole line if no region was selected.

I can take this one if you want.

**Comment by rcoreilly** [comment]
yep emacs and gide use selection.. good idea to just do current line if nothing selected -- should be easy.

**Comment by rohrlich** [comment]
Of course a selected region is required for multi-line comment/uncomment

**Comment by rohrlich** [comment]
Done
