### ISSUE TITLE
Any menu item that leads to a dialog should have ... following menu item name

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#4]
e.g. Open Proj would be Open Proj...

But also, I don't think menu items should be abbreviated

"Open Proj" should be "Open Project..." - better for novices, people who are not native English speakers,  etc.

**Comment by rcoreilly** [comment]
you fixed this right?

**Comment by rohrlich** [comment]
I left open because I probably missed some. I'll just keep a lookout and fix as I see them.

**Comment by rcoreilly** [comment]
ps. don't use the unicode ... elipsis for this -- maybe goland is doing this automatically, but for example we need to be able to search for menu names to insert things after or before, and just using plain ascii is safer there -- some fonts may not render properly etc..

**Comment by rohrlich** [comment]
Sure and I changed one you missed.
