### ISSUE TITLE
Panic trying to remove keyfun from gide keyfuns

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#40]
100% reproducible

**Comment by rohrlich** [comment]
[unrecovered-panic] runtime.fatalpanic() /usr/local/go/src/runtime/panic.go:681 (hits goroutine(83):1 total:1) (PC: 0x40327b0)
Warning: debugging optimized function
	runtime.curg._panic.arg: interface {}(string) "reflect.Value.SetMapIndex: value of type *gide.KeySeq is not ass...+27 more"
   676:	// fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
   677:	// that if msgs != nil, fatalpanic also prints panic messages and decrements
   678:	// runningPanicDefers once main is blocked from exiting.
   679:	//
   680:	//go:nosplit
=> 681:	func fatalpanic(msgs *_panic) {
   682:		pc := getcallerpc()
   683:		sp := getcallersp()
   684:		gp := getg()
   685:		var docrash bool
   686:		// Switch to the system stack to avoid any stack growth, which

**Comment by rcoreilly** [comment]
fixed
