### ISSUE TITLE
dictionary empty 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#41]
I suspect the problem you experienced is founded in not finding the big.txt file from which the starting dictionary is built. There should have been a println to that effect. I have now added a prompt dialog to make it obvious.

I suspect the problem leading to the file not being found is a difference in our file structures. Here is how I am locating the file:
	gopath := os.Getenv("GOPATH")
	bigdatapath := gopath + "/src/github.com/goki/gi/spell/big.txt"

**Comment by rcoreilly** [comment]
in gi/svg/icons.go, this is the proper code -- replace "SrcDir" with "svg.SrcDir" -- actually I'll move it to kit instead as our general "kit" directory, and fix the use in spell

	path, err := SrcDir("github.com/goki/gi/icons")
	if err != nil {
		log.Println(err)
		return err
	}
