### ISSUE TITLE
SegFault: Setting split I had just created

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#45]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff496b40e7]

runtime stack:
runtime.throw(0x494be15, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4764970, 0xc00005eec8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc00005ee98 sp=0xc00005ee60 pc=0x400576e
github.com/goki/gi/oswin/driver/macdriver._Cfunc_startDriver()
	_cgo_gotypes.go:727 +0x41 fp=0xc00005eec8 sp=0xc00005ee98 pc=0x46be5a1
github.com/goki/gi/oswin/driver/macdriver.startDriver()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:105 +0x3b fp=0xc00005ef20 sp=0xc00005eec8 pc=0x46bf4db
github.com/goki/gi/oswin/driver/macdriver.Main(0xc00025a9c0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/macdriver.go:27 +0x35 fp=0xc00005ef30 sp=0xc00005ef20 pc=0x46b99e5
github.com/goki/gi/oswin/driver.main(0xc00025a9c0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver_darwin.go:20 +0x2b fp=0xc00005ef48 sp=0xc00005ef30 pc=0x46c4c1b
github.com/goki/gi/oswin/driver.Main(0xc00025a9c0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b fp=0xc00005ef60 sp=0xc00005ef48 pc=0x46c4bdb
github.com/goki/gi/gimain.Main(0x49864f0)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:24 +0x57 fp=0xc00005ef80 sp=0xc00005ef60 pc=0x46fc607
main.main()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:20 +0x2d fp=0xc00005ef98 sp=0xc00005ef80 pc=0x476301d
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc00005efe0 sp=0xc00005ef98 pc=0x402f647
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00005efe8 sp=0xc00005efe0 pc=0x405b471

goroutine 4 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0x561d408)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0x561d400)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:84 +0x1c2
main.main.func1()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:21 +0x20
github.com/goki/gi/gimain.Main.func1(0x4aed720, 0x55d7020)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:25 +0x24
github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:188 +0x40
created by github.com/goki/gi/oswin/driver/macdriver.driverStarted
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:187 +0x5f

goroutine 39 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc000094480, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:236 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:178 +0xe8

goroutine 5 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc000094520, 0xecb)
	/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc000094510)
	/usr/local/go/src/sync/cond.go:56 +0x92
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0xc000094508, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x77
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).NextEvent(0xc000094480, 0x29f7eb1a47, 0x55fd520)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:104 +0x33
github.com/goki/gi.(*Window).EventLoop(0xc0001e4000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1012 +0x1c3
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:546 +0x66

goroutine 41 [chan receive]:
github.com/goki/gi/giv.TextViewBlink()
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:2509 +0x46
created by github.com/goki/gi/giv.(*TextView).StartCursor
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:2543 +0xf3

goroutine 8 [chan receive]:
github.com/goki/gi.TextFieldBlink()
	/Users/rohrlich/go/src/github.com/goki/gi/textfield.go:676 +0x46
created by github.com/goki/gi.(*TextField).StartCursor
	/Users/rohrlich/go/src/github.com/goki/gi/textfield.go:710 +0xf1

goroutine 99 [runnable]:
reflect.Value.Field(0x4851cc0, 0xc011bfc000, 0x199, 0x0, 0x0, 0x0, 0x4aee7c0)
	/usr/local/go/src/reflect/value.go:810 +0x148
github.com/goki/ki.FlatFieldsValueFunc(0x48d81e0, 0xc011bfc000, 0x4986038, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:935 +0x253
github.com/goki/ki.(*Node).Disconnect(0xc011bfc000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1174 +0x70
github.com/goki/ki.(*Node).DisconnectAll.func1(0x4b189a0, 0xc011bfc000, 0xc, 0x0, 0x0, 0x41cea01)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1198 +0x34
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc011bfc000, 0xc, 0x0, 0x0, 0x4986040, 0x41cea00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:999 +0x6b
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc011be8f00, 0xc, 0x0, 0x0, 0x4986040, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc01061ae88, 0xb, 0x0, 0x0, 0x4986040, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst.func1(0x4b1b520, 0xc01061ae88, 0xa, 0x0, 0x0, 0x48c59a0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1004 +0x59
github.com/goki/ki.(*Node).FuncFields(0xc01061aa80, 0xa, 0x0, 0x0, 0xc00919b8c8)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:963 +0x13a
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc01061aa80, 0xa, 0x0, 0x0, 0x4986040, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1003 +0xf3
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc01060ee88, 0x9, 0x0, 0x0, 0x4986040, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst.func1(0x4b1b520, 0xc01060ee88, 0x8, 0x0, 0x0, 0x48c2880)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1004 +0x59
github.com/goki/ki.(*Node).FuncFields(0xc01060ea80, 0x8, 0x0, 0x0, 0xc00919ba68)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:963 +0x13a
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc01060ea80, 0x8, 0x0, 0x0, 0x4986040, 0x41cea00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1003 +0xf3
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0083d4000, 0x7, 0x0, 0x0, 0x4986040, 0x41cea00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0083cca00, 0x6, 0x0, 0x0, 0x4986040, 0x41cea00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0088a1800, 0x5, 0x0, 0x0, 0x4986040, 0x41cea00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0084b6a00, 0x4, 0x0, 0x0, 0x4986040, 0x41cea00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00b291900, 0x3, 0x0, 0x0, 0x4986040, 0x41cea00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0085f2a80, 0x2, 0x0, 0x0, 0x4986040, 0xc00a4e0500)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00a4e0500, 0x1, 0x0, 0x0, 0x4986040, 0x80)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).DisconnectAll(0xc00a4e0500)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1197 +0x48
github.com/goki/ki.(*Node).Destroy(0xc00a4e0500)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:720 +0xa7
github.com/goki/gi.(*Window).EventLoop(0xc00a4e0500)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1423 +0x67b
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:546 +0x66
rohrlich@MacBook-Pro-4:gide:>

**Comment by rohrlich** [comment]
this time I created a new split and got the crash after saving prefs and closing edit splits dialog

**Comment by rohrlich** [comment]
rohrlich@MacBook-Pro-4:gide:> ./gide
2018/10/25 13:37:22 gi.TextRender SetHTMLPre end tag: mark doesn't match current tag:  for string
	med := []byte("</mark>")
2018/10/25 13:38:49 gi.TextRender SetHTMLPre end tag: mark doesn't match current tag:  for string
			nomu = bytes.Replace(nomu, []byte("</mark>"), nil, -1)
drohrlich@MacBook-Pro-4:gide:> ./gide
2018/10/25 14:11:27 gi.TextRender SetHTMLPre end tag: mark doesn't match current tag:  for string
			nomu = bytes.Replace(nomu, []byte("</mark>"), nil, -1)
rohrlich@MacBook-Pro-4:gide:> LS
Makefile	gide		gide-mac.sh	gide.app	gide.go
rohrlich@MacBook-Pro-4:gide:> open ../../gide.go
rohrlich@MacBook-Pro-4:gide:> ./gide
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1dffff93cd pc=0x7fff38c92fad]

runtime stack:
runtime.throw(0x49575ae, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x476de90, 0xc000065ec8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000065e98 sp=0xc000065e60 pc=0x400598e
github.com/goki/gi/oswin/driver/macdriver._Cfunc_startDriver()
	_cgo_gotypes.go:727 +0x41 fp=0xc000065ec8 sp=0xc000065e98 pc=0x46c5631
github.com/goki/gi/oswin/driver/macdriver.startDriver()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:105 +0x3b fp=0xc000065f20 sp=0xc000065ec8 pc=0x46c656b
github.com/goki/gi/oswin/driver/macdriver.Main(0xc00023ee20)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/macdriver.go:27 +0x35 fp=0xc000065f30 sp=0xc000065f20 pc=0x46c0a75
github.com/goki/gi/oswin/driver.main(0xc00023ee20)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver_darwin.go:20 +0x2b fp=0xc000065f48 sp=0xc000065f30 pc=0x46cbcab
github.com/goki/gi/oswin/driver.Main(0xc00023ee20)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b fp=0xc000065f60 sp=0xc000065f48 pc=0x46cbc6b
github.com/goki/gi/gimain.Main(0x4992268)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:24 +0x57 fp=0xc000065f80 sp=0xc000065f60 pc=0x4703697
main.main()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:20 +0x2d fp=0xc000065f98 sp=0xc000065f80 pc=0x476c53d
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000065fe0 sp=0xc000065f98 pc=0x402f997
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x405b921

goroutine 20 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0x56316c0)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0x56316b8)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:84 +0x1c2
main.main.func1()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:21 +0x20
github.com/goki/gi/gimain.Main.func1(0x4afa880, 0x55eb260)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:25 +0x24
github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:188 +0x40
created by github.com/goki/gi/oswin/driver/macdriver.driverStarted
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:187 +0x5f

goroutine 8 [select, 1 minutes, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc0002e0000, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:236 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:178 +0xe8

goroutine 37 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0002e00a0, 0x126)
	/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0002e0090)
	/usr/local/go/src/sync/cond.go:56 +0x92
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0xc0002e0088, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x77
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).NextEvent(0xc0002e0000, 0xc12, 0x70e)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:104 +0x33
github.com/goki/gi.(*Window).EventLoop(0xc0000e0000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1089 +0x1cc
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:623 +0x9d

goroutine 67 [runnable]:
reflect.typedmemmove(0x47df9e0, 0xc008ff5000, 0xc00c5bdc18)
	/usr/local/go/src/runtime/mbarrier.go:177 +0x4e
reflect.packEface(0x47df9e0, 0xc00c5bdc18, 0x191, 0x486a96e, 0xb)
	/usr/local/go/src/reflect/value.go:119 +0x9f
reflect.valueInterface(0x47df9e0, 0xc00c5bdc18, 0x191, 0x1, 0x1, 0x0)
	/usr/local/go/src/reflect/value.go:1008 +0xe1
reflect.Value.Interface(0x47df9e0, 0xc00c5bdc18, 0x191, 0x5, 0x47df9e0)
	/usr/local/go/src/reflect/value.go:978 +0x44
github.com/goki/ki.FlatFieldsValueFunc(0x48dc8c0, 0xc00c5bd300, 0x4991db0, 0x48dc8c0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:939 +0x2ab
github.com/goki/ki.FlatFieldsValueFunc(0x48e33e0, 0xc00c5bd300, 0x4991db0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:944 +0x48c
github.com/goki/ki.(*Node).Disconnect(0xc00c5bd300)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1174 +0x70
github.com/goki/ki.(*Node).DisconnectAll.func1(0x4b25980, 0xc00c5bd300, 0xc, 0x0, 0x0, 0x41cf0e0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1198 +0x34
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00c5bd300, 0xc, 0x0, 0x0, 0x4991db8, 0x41cf000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:999 +0x6b
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0092f8000, 0xc, 0x0, 0x0, 0x4991db8, 0x491b700)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0099cce88, 0xb, 0x0, 0x0, 0x4991db8, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst.func1(0x4b28500, 0xc0099cce88, 0xa, 0x0, 0x0, 0x48d0ba0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1004 +0x59
github.com/goki/ki.(*Node).FuncFields(0xc0099cca80, 0xa, 0x0, 0x0, 0xc007d27770)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:963 +0x13a
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0099cca80, 0xa, 0x0, 0x0, 0x4991db8, 0x491b700)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1003 +0xf3
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00b469908, 0x9, 0x0, 0x0, 0x4991db8, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst.func1(0x4b28500, 0xc00b469908, 0x8, 0x0, 0x0, 0x48cda80)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1004 +0x59
github.com/goki/ki.(*Node).FuncFields(0xc00b469500, 0x8, 0x0, 0x0, 0xc007d27910)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:963 +0x13a
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00b469500, 0x8, 0x0, 0x0, 0x4991db8, 0x41cf000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1003 +0xf3
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc006f5e000, 0x7, 0x0, 0x0, 0x4991db8, 0x41cf000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc006f54a00, 0x6, 0x0, 0x0, 0x4991db8, 0x41cf000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc006f4e000, 0x5, 0x0, 0x0, 0x4991db8, 0x41cf000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc006f46000, 0x4, 0x0, 0x0, 0x4991db8, 0x41cf000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc006cbcf00, 0x3, 0x0, 0x0, 0x4991db8, 0x41cf000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc006cc8a80, 0x2, 0x0, 0x0, 0x4991db8, 0xc006cbc000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc006cbc000, 0x1, 0x0, 0x0, 0x4991db8, 0x80)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).DisconnectAll(0xc006cbc000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1197 +0x48
github.com/goki/ki.(*Node).Destroy(0xc006cbc000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:720 +0xa7
github.com/goki/gi.(*Window).EventLoop(0xc006cbc000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1511 +0x815
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:623 +0x9d

goroutine 10 [chan receive]:
github.com/goki/gi.TextFieldBlink()
	/Users/rohrlich/go/src/github.com/goki/gi/textfield.go:676 +0x46
created by github.com/goki/gi.(*TextField).StartCursor
	/Users/rohrlich/go/src/github.com/goki/gi/textfield.go:710 +0xf1
rohrlich@MacBook-Pro-4:gide:>

**Comment by rcoreilly** [comment]
not sure I got the same crash -- got a reliable one by making a new (non-duplicate) split, and then using pencil to edit the slice, added 5 elements, went back to main editor - that is when it crashed on me.  after fix I was able to do several times no crashing.. please test..

**Comment by rohrlich** [comment]
No crash. Tried both reasonable and unreasonable use cases.
