### ISSUE TITLE
Need mechanism for supplementing dictionary with specific word sets

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#59]
For example we might want to add neuroscience terms or programming jargon.

We can start by adding some texts to the default training text but it would be easy to allow users to point to text they want to train on.

**Comment by rohrlich** [comment]
Proposal:
- Directory in Library/gide that holds files from which to build the spelling model
- Menu item to rebuild spelling model which would move old model out of way and build a new one from whatever files were in the directory.

**Comment by rcoreilly** [comment]
Seems like you shouldn't need to put stuff in Library/gide -- just point it to any dir?  This is a one-time thing, and then you get your model which is saved right?

also, if the thing isn't using multi-word context (right?) then just using a dictionary seems like it is the same as using raw text??  I don't get why that wouldn't be the case.  unless there are multiple spellings and frequency matter...

**Comment by rohrlich** [comment]
The spell code needs to know where to look for the files so we could start with a specific location and let users change it in prefs. The default would like be just some english prose but we might want to add some neuroscience text, emergent docs, etc depending on what you are composing. The alternative is to keep clicking  the "learn" button in the spell checker.

As for frequency, yes it matters, there is a setting for how many times a word needs to be seen before suggestions are stored in the model. If you set that to "1" then the model can get very big (I can't give you stats at this time) because it will keep suggestions for rare words.

I guess we need to talk more about the use cases we care about.

**Comment by rcoreilly** [comment]
Is this a one-time thing or not?  if so, just open the fileview dialog and have someone choose it.  if not, I don't understand.. and does it take forever to load the model if it is big?  definitely matters how big is big -- if it is reasonably fast, then I personally would be fine having a big file..

**Comment by rcoreilly** [comment]
sounds good.  and by "one time thing" i mean: it isn't something that is run *every time* you startup, to regenerate the dictionary.. in which case, I think it makes sense to just have the user choose a directory or file using fileview dialog, and not have to put things in a special place..

**Comment by rohrlich** [comment]
Just noticed this API of interest if you still want to build spell model from dictionary

// Manually set the count of a word. Optionally trigger the
// creation of suggestion keys for the term. This function lets
// you build a model from an existing dictionary with word popularity
// counts without needing to run "TrainWord" repeatedly
func (model *Model) SetCount(term string, count int, suggest bool) {

**Comment by rohrlich** [comment]
You can now select a file to train on to supplement the existing model
todo:
- Add action to move aside spelling model and create a new one
- If the user selects a directory instead of a file, train on all .txt files in the directory

**Comment by rohrlich** [comment]
Closing and opening narrower issue
