### ISSUE TITLE
Reopening a project should reopen the files being edited when project was closed

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#6]

**Comment by rcoreilly** [comment]
I really don't like those kinds of options, but somehow other people do.  Maybe if you have a very  small project with just a couple of files it would make sense. Anyway, maybe you can impl if you like it! :)

**Comment by rohrlich** [comment]
Wasn't thinking about an option. Just like to have my project open in the state I left it in. The same logic as having your zoom, window sizes, font, etc as you left them. Could be an option if you like the contents of your windows to disappear when you close the project.

**Comment by rcoreilly** [comment]
typically I'm doing different things each time I work on a project, and I don't want to have all the "cruft" lying around from previous session...
