### ISSUE TITLE
Add "cycle windows" and keyfun for it - on Mac it is cmd + back quote 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#60]
I started to implement this by adding a case for WindowEvent (in addition to existing resize and paint) but it didn't catch all window focus events. What I need is to always know which window is front so I can cycle through the AllWindows list.

**Comment by rcoreilly** [comment]
I JUST committed the fix that properly tracks DeFocus, so now you can just check GotFocus flag and that will be the one.. and, btw, this one actually SHOULD be in gi, not gide!  it should just be a special keycode in gi/window.go under the lowpri keys method.  need to add a key mapping for it in keyfun.go -- need to run go generate after doing so -- that updates the string converter for loading / saving / gui.

**Comment by rcoreilly** [comment]
ps it needs to be all under the proper mutex for traversing the windows list -- I can do all this later tonight if you don't get to it -- let me know..
