### ISSUE TITLE
Selecting file from Edit menu fails to open file in single edit frame

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#61]

**Comment by rohrlich** [comment]
Closing - now working!

**Comment by rohrlich** [comment]
Happened again -

- Set split to "Edit"
- open files into both frames
- make the rightmost be the active frame (not  sure about this step)
- change split to small
- Select a file from the Edit menu
- active view does not update to selected file
- may actually hang

**Comment by rcoreilly** [comment]
fixed -- after setting new splits, is ensures that active textview is visible.
