### ISSUE TITLE
Crash on closing preference windows

### ISSUE THREAD

**Issue by apmon** [goki/gide#64]
I had two project preference windows open and then closed both and wanted to switch over to the main window again at which point gide crashed.

goroutine 1 [running, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).MainMenu(...)
	...go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:439
github.com/goki/gi/oswin/driver/macdriver.menuFired(0x5d59460, 0x5d60911, 0x300000016)
	...go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:653 +0x7d
github.com/goki/gi/oswin/driver/macdriver._cgoexpwrap_d70297deb232_menuFired(0x5d59460, 0x5d60911, 0x300000016)
	_cgo_gotypes.go:969 +0x45
github.com/goki/gi/oswin/driver/macdriver._Cfunc_startDriver()
	_cgo_gotypes.go:721 +0x41
github.com/goki/gi/oswin/driver/macdriver.startDriver()
	...go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:106 +0x3b
github.com/goki/gi/oswin/driver/macdriver.Main(0xc4202c20a0)
	...go/src/github.com/goki/gi/oswin/driver/macdriver/macdriver.go:27 +0x36
github.com/goki/gi/oswin/driver.main(0xc4202c20a0)
	...go/src/github.com/goki/gi/oswin/driver/driver_darwin.go:20 +0x2b
github.com/goki/gi/oswin/driver.Main(0xc4202c20a0)
	...go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b
github.com/goki/gi/gimain.Main(0x4995ee8)
	...go/src/github.com/goki/gi/gimain/gimain.go:26 +0x5c
main.main()
	...go/src/github.com/goki/gide/cmd/gide/gide.go:20 +0x2d

**Comment by rcoreilly** [comment]
looks like a menu action fired after window died.. hopefully got better protected now..  reopen if it happens again.
