### ISSUE TITLE
Spelling enhancements

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#68]
- Add action to move aside spelling model and create a new one
- If the user selects a directory instead of a file, train on all .txt files in the directory

**Comment by rcoreilly** [comment]
Not sure if we need these anymore -- current strategy is now to ship *my* "pretty good" dictionary -- still need a better soln for other languages though.  I will be doing check on fairly large corpora over next few weeks so it should be pretty good by then, at least for our cog neuro users :)
