### ISSUE TITLE
Scrollbar appearing in tabview when it shouldn't - occurs changing tabs

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#75]
Steps -
- Open README
- Click spelling... button
- Go to tabs and click "console" tab
- Now click spelling tab
![screen shot 2018-11-07 at 8 34 58 am](https://user-images.githubusercontent.com/22350787/48141399-11541780-e268-11e8-9f96-f0289fa97097.png)

**Comment by rcoreilly** [comment]
fixed with visbility fixes..
