### ISSUE TITLE
Abysmal install experience, wrong docs

### ISSUE THREAD

**Issue by ohir** [goki/gide#76]
1. `go get -u ...` will update  **ALL and ANY** things present on GOPATH. Including your private repos.

WRONG:  `go get -u ...` 
PROPER: `cd $GOPATH/src/github.com/goki/gide/cmd/gide && go get -u ./...`

2. The install instruction on wiki should first list a canonical way: 
```
GOBIN=/path/to/writable/bin go get -u github.com/goki/gide/...
```

It will pull, update and install (to GOBIN provided) in one shot. [It really does. Checked with rm `-rf $GOPATH/src/github.com/goki && rm $GOBIN/gide && go get -u github.com/goki/gide/...`]

Only then wiki should mention step by step instruction

As there are no go-gettable files in main dirs usual 'ol `go get something` one by one will bark. Warn novice user. Or just stay with [^2] as the only way listed. People who do know how to get go get make download/update chores by hand usually know how to build and install :)

**Comment by rcoreilly** [comment]
thanks for the fixes -- wiki updated.

**Comment by ohir** [comment]
Still wrong: **is** `go get [-u] ./ ...` **should be**  `go get [-u] ./...` (no space - it is a path)

**Comment by rcoreilly** [comment]
thanks -- hopefully got it right now!
