### ISSUE TITLE
gide won't start (32bit windows 7)

### ISSUE THREAD

**Issue by fgergo** [goki/gide#78]
on 32bit windows 7:

D:\go\src\github.com\goki\gide\cmd\gide>go get ...
..\..\..\..\alecthomas\chroma\cmd\chroma\main.go:16:2: cannot find package "github.com/mattn/go-colorable" in any of:
        c:\go\src\github.com\mattn\go-colorable (from $GOROOT)
        d:\go\src\github.com\mattn\go-colorable (from $GOPATH)
..\..\..\..\alecthomas\chroma\cmd\chroma\main.go:17:2: cannot find package "github.com/mattn/go-isatty" in any of:
        c:\go\src\github.com\mattn\go-isatty (from $GOROOT)
        d:\go\src\github.com\mattn\go-isatty (from $GOPATH)
..\..\..\..\alecthomas\chroma\cmd\chroma\main.go:18:2: cannot find package "gopkg.in/alecthomas/kingpin.v3-unstable" in any of:
        c:\go\src\gopkg.in\alecthomas\kingpin.v3-unstable (from $GOROOT)
        d:\go\src\gopkg.in\alecthomas\kingpin.v3-unstable (from $GOPATH)
..\..\..\..\aymerick\douceur\inliner\element.go:6:2: cannot find package "github.com/PuerkitoBio/goquery" in any of:
        c:\go\src\github.com\PuerkitoBio\goquery (from $GOROOT)
        d:\go\src\github.com\PuerkitoBio\goquery (from $GOPATH)
..\..\..\gi\examples\marbles\graph.go:16:2: cannot find package "github.com/Knetic/govaluate" in any of:
        c:\go\src\github.com\Knetic\govaluate (from $GOROOT)
        d:\go\src\github.com\Knetic\govaluate (from $GOPATH)

D:\go\src\github.com\goki\gide\cmd\gide>go get -u ...

D:\go\src\github.com\goki\gide\cmd\gide>go build

D:\go\src\github.com\goki\gide\cmd\gide>gide
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x401eab]

goroutine 1 [running]:
runtime/internal/atomic.Load64(0x13133cf4, 0x13022000, 0xc0c904)
        c:/go/src/runtime/internal/atomic/asm_386.s:188 +0xb
github.com/goki/ki/bitflag.SetMaskAtomic(0x13133cf4, 0x1, 0x0)
        d:/go/src/github.com/goki/ki/bitflag/bitflag.go:32 +0x21
github.com/goki/ki/bitflag.SetAtomic(0x13133cf4, 0x13070b6c, 0x1, 0x1)
        d:/go/src/github.com/goki/ki/bitflag/bitflag.go:99 +0x4d
github.com/goki/ki.(*Node).SetFlag(0x13133ce4, 0x13070b6c, 0x1, 0x1)
        d:/go/src/github.com/goki/ki/node.go:767 +0x3e
github.com/goki/ki.(*Node).Init.func1(0xb909a0, 0x1325f8c0, 0xe35380, 0xbc1740, 0xb7f04b, 0x4, 0x0, 0x0, 0xe35380, 0xb909a0, ...)
        d:/go/src/github.com/goki/ki/node.go:84 +0x116
github.com/goki/ki.FlatFieldsValueFunc(0xc1f3e0, 0x13133400, 0x1305bd94, 0xc1f3e0)
        d:/go/src/github.com/goki/ki/node.go:976 +0x2ba
github.com/goki/ki.FlatFieldsValueFunc(0xc216c0, 0x13133400, 0x1305bd94, 0x1801920)
        d:/go/src/github.com/goki/ki/node.go:971 +0x358
github.com/goki/ki.(*Node).Init(0x13133400, 0xe55ca0, 0x13133400)
        d:/go/src/github.com/goki/ki/node.go:80 +0xbb
github.com/goki/ki.(*Node).InitName(0x13133400, 0xe55ca0, 0x13133400, 0xc88889, 0x11)
        d:/go/src/github.com/goki/ki/node.go:95 +0x31
github.com/goki/gi/svg.MakeDefaultIcons(0xb70e40)
        d:/go/src/github.com/goki/gi/svg/icons.go:255 +0xb6
github.com/goki/gi/svg.init.0()
        d:/go/src/github.com/goki/gi/svg/icons.go:25 +0x50

What shall I do differently to have gide running?

**Comment by rcoreilly** [comment]
this is a rather strange error -- code already has a check for nil right before so it is unclear how it could be nil (and shouldn't be nil in the first place).  seems like perhaps some kind of addressing error??   Unfortunately I don't have access to a windows 7 32bit machine or VM or anything, so I don't know how I could debug it.  if you can pull it up in the delve debugger and investigate that is probably the best way forward.

**Comment by fgergo** [comment]
iiuc delve won't work on 32bit systems: so more print() are be needed, for that I don't have time atm.

also other interesting line in stack trace:
d:/go/src/github.com/goki/ki/node.go:767
and d:/go/src/github.com/goki/ki/node.go has only 700 lines.

ideas?

**Comment by fgergo** [comment]
iiuc delve won't work on 32bit systems: so more print() are be needed, for that I don't have time atm.

**Comment by rcoreilly** [comment]
it may well be that it only runs on 64bit because atomic.Load64 is only supported on 64bit.  if that is the case, there is not an easy fix as our bit flags require atomic updating and thus this function.

I'm going to close for now..
