### ISSUE TITLE
Minimizing all windows causes hang

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#79]
Same result  with one window or multiple - key is minimizing all

Not getting stack trace in this situation - not sure why

(dlv) debug
Command failed: command not available
(dlv) continue
received SIGINT, stopping process (will not forward signal)
Stopped at: 0x7fff65e32a16
=>no source available
(dlv)

**Comment by rohrlich** [comment]
Not 100% reproducible

**Comment by rcoreilly** [comment]
works now it seems.
