### ISSUE TITLE
Recents menu empty

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#8]
I walked the code and the paths are read correctly from the saved json so perhaps the problem is with the menu. I assumed at first it was a stale prefs file but no that isn't it.

**Comment by rcoreilly** [comment]
the menu works fine for the "local" main menu -- in this menu, you get a JIT notification step from the first menu and that is when it fills out the sub-menu with current state.  I'll see if we can somehow get that intermediate step from the mac menus.  meanwhile, use the local one, which will be what users on other platforms see.

**Comment by rohrlich** [comment]
I missed where to turn that on and I don't see it in any of the prefs

**Comment by rcoreilly** [comment]
gogi prefs, main window, Params

**Comment by rohrlich** [comment]
Got it, thanks!

**Comment by rcoreilly** [comment]
another case of Mac main menu deprecation :)
