### ISSUE TITLE
Trying to invoke exec cmd on root causes hang

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#85]

**Comment by rohrlich** [comment]
FileNode() returns nil for root, now checking for fn == nil so we don't hang but is this what we want? Shouldn't we be able to exec commands on root?

**Comment by rcoreilly** [comment]
yeah it should return the filenode for the top-level path..  I guess you just don't want to be able to do delete there.. and probably not rename either?  new file, new folder work.  in general while you're in that code, might be good to cleanup rest of the directory-level stuff which was just not impl -- e.g., delete to delete all, and looks like there are some minor issues with running commands on a sub-folder..

**Comment by rcoreilly** [comment]
ps. in general "causes hang" -> "crashes" -- it only hangs on goland when it takes you to the debugger, right?

**Comment by rcoreilly** [comment]
Just looked into this: the problem is that we make a new gide.FileNode type but NOT a new FileTree -- so that doesn't convert.. just added some special case code to deal with root..
