### ISSUE TITLE
Actions on file nodes should go through version control

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#88]
another one that I can't seem to find, about making those actions e.g., delete, rename go through version control commands if VCS is active (git, svn etc). probably cleanest to just move the VCS stuff into gi -- would be generally useful for all such filetree functionality to be VCS aware. Then can just set the VCS state etc on the FileTree root node or something like that, if it detects a .git file etc. Logic is all already in gide, just need to move it and apply it..

**Comment by rohrlich** [comment]
So are you thinking that selecting delete would prompt the user "delete from git/svn"? Or in the case of new file prompt for "add to git/svn?". Here is what GoLand does.
![screen shot 2018-12-10 at 8 32 29 pm](https://user-images.githubusercontent.com/22350787/49776802-d441d180-fcba-11e8-84f2-a0d040715340.png)

**Comment by rcoreilly** [comment]
for new file, yeah it would be good to just simply add an arg with a default value of true that says "Add To Version Control" or something like that, along with the filename prompt that is already there.  Likewise for the delete -- there is already a prompt, and it can just add a bool to delete from VCS.  It looks like Git already DOES do the delete automatically but wouldn't hurt to just add it -- I'm pretty sure svn does not.

and similarly for rename -- that definitely would benefit from using the vcs command.

**Comment by rohrlich** [comment]
In looking at this it seems like maybe we need to move the exec cmd code down to gi so that actions on the file tree can make calls on git/svn. Otherwise I think it means having filetree calls in gide for delete, add, etc that would do the exec cmd part and the local file part would be done in giv. In some cases like delete git my handle both but in the case of add you would add the file locally and then make the git/svn call. What do you think?

**Comment by rcoreilly** [comment]
don't want to move all that down there -- that is more general purpose / extensible etc.  How about just making a simple map of the commands for each version control type for just the basic add, delete, rename commands, and directly call os exec: https://golang.org/pkg/os/exec/#example_Cmd_CombinedOutput  and just println the output to stdout -- then it will show up in console in gide which is fine.

**Comment by rohrlich** [comment]
That sounds good will do this next.

**Comment by rohrlich** [comment]
Found after adding version control that rename is buggy so backtracking to fix those. Add, Dupe and Delete have version control now.

**Comment by rcoreilly** [comment]
yeah overall it is not working as expected for me -- I couldn't delete something at one point (and then it did work later) and also couldn't add -- that was after doing a move of a file into a subdir.  and the add prompt when making a new file is still not mentioning the name of the new file I think.. and not sure it is doing the add..  would be good to thoroughly test  dnd should be working ok now btw -- has been in my tests on Pi editor, but haven't tested much in filetree..

**Comment by rcoreilly** [comment]
a new case I just encountered: if you open gide on a parent directory of several repositories (as I just did getting all the github wikis into a wikis directory, with each wiki under that) then there isn't a root-level .git file but there are .git files in each of the subdirs... kind of a pain but would be good to support this config at some point..

**Comment by rcoreilly** [comment]
this is all fixed now -- goes up directories to find parent repo, uses that.
