### ISSUE TITLE
Second tab panel issues

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#89]
1 - If second tab empty -- If I have a single tab panel, and I have print stmts in my code, when the print is encountered it opens the console tab in the single panel and switches to it. If I have 2 tab panels the console tab never appears!
2 - Is there a way to move items to second tab
3 - My recollection is that the second panel would never hold more than one tab and there would be a means to decide which it was
4 - I really would like the secondary to be below rather than along side.

**Comment by rcoreilly** [comment]
1. console tab should appear at startup, and if you don't want to see those messages you can close it, and reopoen later (there is a menu item to open it).  Not sure why it wouldn't appear with 2 panels but I can look into that..

2. Not yet..

3. No, 2nd panels is the "vis" tabs -- visualizations -- like the 3D view / graph view / etc.  We don't have any of those supported yet, so it really isn't doing anything..

4. that is possible and not that hard, so once we actually have some relevant use of it, we can figure out if it is worth adding the relevant controls / configs etc to make that happen.. the idea however was that for many views, esp net view, you would want it to be full size, and that the best tradeoff would be to lose one of the editor panels when using the 2 tabs..  also, you will be able to easily arrange multiple graphs per vis tab, so the full size will likely be beneficial there.. but again we can see.

**Comment by rcoreilly** [comment]
get rid of second tab panel!  our mission has changed an any vis will be external to the main editor window.

**Comment by rcoreilly** [comment]
gone!
