### ISSUE TITLE
Clicking on link in FindView doesn't highlight text in source

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#90]
Clicking link in FindView's textview sets the cursor in source at link and then returns focus to FindView. -- Would be better to leave focus in source code and select the source text that was linked to or highlight differently so it can be distinguished from all the other found instances. Just making the source the active view would help but the cursor isn't much to distinguish the found item.

**Comment by rcoreilly** [comment]
it is not too hard to select back to textview.
