### ISSUE TITLE
Add Revert to last commit

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#95]
What are the steps here other than the call to the repository - do we need to close the file first and then call update files. What if the file is in an active view? Would it work to do the repo call and then call RevertActiveView?

**Comment by rcoreilly** [comment]
I'm pretty sure just doing the repo revert and then calling Revert on the specific filenode would work.  You can't count on it being the active view, right?  better to just operate directly on the textbuf for the relevant filenode.  the fact that the giv filenode has the textbuf is really key -- that is the **only** thing that matters -- any relevant load / revert / etc on the textbuf automatically updates the views so you should always be thinking in terms of those textbufs!  in this way, all the basic VCS stuff can all be managed by the filetree and gide can just refer / use the filetree impl of everything (and indeed it operates primarily on the filenodes anyway).

**Comment by rohrlich** [comment]
done

**Comment by rohrlich** [comment]
hmm, not working now

**Comment by rcoreilly** [comment]
it is Checkout Git and it works
